rapIds = [('RapCaviar', '37i9dQZF1DX0XUsuxWHRQd', 'United States'),
               ('Get Turnt', '37i9dQZF1DWY4xHQp97fN6', 'United States'),
               ('Power Workout', '37i9dQZF1DWUVpAXiEPK8P', 'United States'),
               ('Most Necessary', '37i9dQZF1DX2RxBh64BHjQ', 'United States'),
               ('Hot Rhythmic', '37i9dQZF1DWYs83FtTMQFw', 'United States'),
               ('Love, Sex, & Water', '37i9dQZF1DWX3387IZmjNa', 'United States'),
               ('Signed XOXO', '37i9dQZF1DX2A29LI7xHn1', 'United States'),
               ('Channel X', '37i9dQZF1DX4y8h9WqDPAE', 'United States'),
               ('Workout Twerkout', '37i9dQZF1DX0HRj9P7NxeE', 'United States'),
               ('The Realest Down South', '37i9dQZF1DX0Tkc6ltcBfU', 'United States'),
               ('Singled Out', '37i9dQZF1DX8f6LHxMjnzD', 'United States'),
               ('The Newness', '37i9dQZF1DWUzFXarNiofw', 'United States'),
               ('Mind Right', '37i9dQZF1DX5hR0J49CmXC', 'United States'),
               ('Clout Culture', '37i9dQZF1DWVk7x1ClrO0Y', 'United States'),
               ('Hip-Hop Central', '37i9dQZF1DWY6tYEFs22tT', 'Canada'),
               ('R&B Right Now', '37i9dQZF1DX2WkIBRaChxW', 'Canada'),
               ('New Music Now', '37i9dQZF1DXbpmT3HUTsZm', 'Canada'),
               ('Top Hits Deutschland', '37i9dQZF1DX4jP4eebSWR9', 'Germany'),
               ('Swag!', '37i9dQZF1DX2YSAZIuAiB1', 'Germany'),
               ('Hot Hits Australia', '37i9dQZF1DWXXs9GFYnvLB', 'Australia'),
               ('Urban Flavour', '37i9dQZF1DXa49JU4zzjb9', 'Australia'),
               ('Hot Hits New Zealand', '37i9dQZF1DWY5Nosj13GLt', 'New Zealand'),
               ('Hot Hip Hop', '37i9dQZF1DWVPRVPGc4ZVv', 'France'),
               ('Hot Hits UK', '37i9dQZF1DWY4lFlS4Pnso', 'United Kingdom'),
               ('Rap Workout', '37i9dQZF1DX76t638V6CA8', 'United Kingdom'),
               ('Grime Shutdown', '37i9dQZF1DWSOkubnsDCSS', 'United Kingdom'),
               ('Rap UK', '37i9dQZF1DX6PKX5dyBKeq', 'United Kingdom'),
               ('Who We Be', '37i9dQZF1DXcDoDDetPsEg', 'United Kingdom'),
               ('Alternative Hip Hop', '37i9dQZF1DWTggY0yqBxES', 'United Kingdom'),
               ('Afro Bashment', '37i9dQZF1DXdeMORbC1XNa', 'United Kingdom'),
               ('Bedroom Jams', '37i9dQZF1DX0QKpU3cGsyb', 'Netherlands'),
               ('Mellow Bars', '37i9dQZF1DWT6MhXz0jw61', 'Netherlands'),
               ('Top Hits NL', '37i9dQZF1DWSBi5svWQ9Nk', 'Netherlands'),
               ('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
               ('BAE', '37i9dQZF1DWX3387IZmjNa', 'United States'),
               ('Off The Strength', '37i9dQZF1DXaxIqwkEGFEh', 'N/A'),
               ('Shisha Lounge', '37i9dQZF1DX68x6hand0cN', 'N/A'),
               ('Locked In', '37i9dQZF1DWTl4y3vgJOXW', 'N/A'),
               ('Cali Fire', '37i9dQZF1DWSvKsRPPnv5o', 'United States'),
               ('Hip-Hop Mixtape', '37i9dQZF1DWVdgXTbYm2r0', 'N/A'),
               ('Anti Pop', '37i9dQZF1DWWqNV5cS50j6', 'N/A'),
               ('Spilled Ink', '37i9dQZF1DWSTeI2WWFaia', 'N/A'),
               ('State of Mind', '37i9dQZF1DX1YPTAhwehsC', 'N/A'),
               ('A1 Hip-Hop', '37i9dQZF1DX0sDai2F5jCQ', 'N/A'),
               ('Hip-Hop Favourites', '37i9dQZF1DX48TTZL62Yht', 'N/A'),
               ('Hip-Hop Yoga', '37i9dQZF1DX4FJyIpen2Yf', 'N/A'),
               ('Beats & Rhymes', '37i9dQZF1DXcA6dRp8rwj6', 'N/A'),
               ('Treino Hip-Hop', '37i9dQZF1DX9wPYtCQ8Q0s', 'Brazil'),
               ('Internet People', '37i9dQZF1DX6OgmB2fwLGd', 'N/A'),
               ('Hip Hop Mix', '37i9dQZF1DWXRPjCBAuFj3', 'N/A'),
               ('100', '37i9dQZF1DWXfgo3OOonqa', 'Sweden')]


indieIds = [('MostBeautifulSongsintheWorld', '37i9dQZF1DX9Z3vMB2b8im', 'United Kingdom'),
               ('Infinite Acoustic', '37i9dQZF1DX6z20IXmBjWI', 'N/A'),
               ('Ultimate Indie', '37i9dQZF1DX2Nc3B70tvx0', 'United States'),
               ('Roots Rising', '37i9dQZF1DWYV7OOaGhoH0', 'N/A'),
               ('Hanging Out and Relaxing', '37i9dQZF1DXci7j0DJQgGp', 'United States'),
               ('Totally Stress Free', '37i9dQZF1DWT7XSlwvR1ar', 'United States'),
               ('Wild and Free', '37i9dQZF1DX5Q5wA1hY6bS', 'United States'),
               ('Young & Free', '37i9dQZF1DXca8AyWK6Y7g', 'United States'),
               ('Indie Pop', '37i9dQZF1DWWEcRhUVtL8n', 'United States'),
               ('All New Indie', '37i9dQZF1DXdbXrPNafg9d', 'United States'),
               ('POLLEN', '37i9dQZF1DWWBHeXOYZf74', 'N/A'),
               ('The New Alt', '37i9dQZF1DX82GYcclJ3Ug', 'United States'),
               ('Fruhlingsgefuhle', '37i9dQZF1DWZESE3fHLhmD', 'Germany'),
               ('Fresh Finds', '37i9dQZF1DWWjGdmeTyeJ6', 'United States'),
               ('Cafe Libros', '37i9dQZF1DWZkMGGysxknj', 'N/A'),
               ('Fresh Folk', '37i9dQZF1DXaUDcU6KDCj4', 'N/A'),
               ('Lorem', '37i9dQZF1DXdwmD5Q7Gxah', 'N/A'),
               ('Front Left', '37i9dQZF1DX5WTH49Vcnqp', 'Australia'),
               ('Fruhlings Chillout', '37i9dQZF1DXaIrEwuQ3hyy', 'Germany'),
               ('Wake Up and Smell the Coffee', '37i9dQZF1DXcxacyAXkQDu', 'Sweden'),
               ('Your Coffee Break', '37i9dQZF1DWYqdkUCLfYzP', 'United Kingdom'),
               ('Its ALT Good!', '37i9dQZF1DX2SK4ytI2KAZ', 'United States'),
               ('Indie Stage', '37i9dQZF1DX1hBl8Jfe9dd', 'Brazil'),
               ('The Stress Buster', '37i9dQZF1DWUvQoIOFMFUT', 'United Kingdom'),
               ('Totally Alt', '37i9dQZF1DXa6YOhGMjjgx', 'United States'),
               ('Rockin Vibes', '37i9dQZF1DX2aneNMeYHQ8', 'N/A'),
               ('Feelgood Indie', '37i9dQZF1DWWM6GBnxtToT', 'Germany'),
               ('OFF POP', '37i9dQZF1DX07Bg0Q5GozA', 'Germany'),
               ('Melancolia Indie', '37i9dQZF1DX4jSp9PHDkEC', 'Mexico'),
               ('The Indie List', '37i9dQZF1DWVTKDs2aOkxu', 'United Kingdom'),
               ('Coffee and Chill', '37i9dQZF1DXa1BeMIGX5Du', 'Australia'),
               ('Akustischer Fruhling', '37i9dQZF1DX8FmtpZigIQk', 'Germany'),
               ('Arkada Calsın', '37i9dQZF1DXcy0AaElSqwE', 'Turkey'),
               ('Apero', '37i9dQZF1DWZk2SPZ3bugX', 'N/A'),
               ('Lost In The Woods', '37i9dQZF1DWYm3dUe8iSaq', 'United Kingdom'),
               ('Gentle Acoustic', '37i9dQZF1DXdxjdZwLamNx', 'Australia'),
               ('Your Office Stereo', '37i9dQZF1DX31KQt69Gaqf', 'United Kingdom'),
               ('Van Life', '37i9dQZF1DX2ogDiL6nZJr', 'N/A')]

electronicIds = [('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
                 ('mint', '37i9dQZF1DX4dyzvuaRJ0n', 'United States'),
                 ('Motivation Mix', '37i9dQZF1DXdxcBWuJkbcy', 'United States'),
                 ('Dance Party', '37i9dQZF1DXaXB8fQg7xif', 'N/A'),
                 ('Dance Hits', '37i9dQZF1DX0BcQWzuB7ZO', 'United States'),
                 ('Cardio', '37i9dQZF1DWSJHnPb1f0X3', 'United States'),
                 ('Dance Rising', '37i9dQZF1DX8tZsk68tuDw', 'United States'),
                 ('Power Hour', '37i9dQZF1DX32NsLKyzScr', 'N/A'),
                 ('Lounge Soft House', '37i9dQZF1DX82pCGH5USnM', 'N/A'),
                 ('Main Stage', '37i9dQZF1DX7ZUug1ANKRP', 'Germany'),
                 ('Techno Bunker', '37i9dQZF1DX6J5NfMJS675', 'N/A'),
                 ('Wake Up Happy', '37i9dQZF1DX0UrRvztWcAU', 'N/A'),
                 ('Young & Free', '37i9dQZF1DXca8AyWK6Y7g', 'United States'),
                 ('Chillout Lounge', '37i9dQZF1DWTvNyxOwkztu', 'Germany'),
                 ('Happy Beats', '37i9dQZF1DWSf2RDTDayIx', 'N/A'),
                 ('Massive Dance Hits', '37i9dQZF1DX5uokaTN4FTR', 'N/A'),
                 ('Partyhymnen', '37i9dQZF1DX9EM98aZosoy', 'Germany'),
                 ('Stimmungsmacher', '37i9dQZF1DX3Ebqev5IkYU', 'Germany'),
                 ('You Can Do It', '37i9dQZF1DX1gcrZ1xC96D', 'N/A'),
                 ('Night Rider', '37i9dQZF1DX6GJXiuZRisr', 'N/A'),
                 ('Happy Dance', '37i9dQZF1DX4uPi2roRUwU', 'N/A'),
                 ('Heart Beats', '37i9dQZF1DWSRc3WJklgBs', 'N/A'),
                 ('UK House Music', '37i9dQZF1DWSrVdvTl1tVY', 'United Kingdom'),
                 ('Bass Arcade', '37i9dQZF1DX0hvSv9Rf41p', 'N/A'),
                 ('All Night Dance Party', '37i9dQZF1DX0MXH7aN4Pxn', 'N/A'),
                 ('Metropolis', '37i9dQZF1DX8CopunbDxgW', 'N/A'),
                 ('Impulso Creativo', '37i9dQZF1DWWnMZKMl7SWB', 'Spain'),
                 ('Workout Beats', '37i9dQZF1DWUSyphfcc6aL', 'Australia'),
                 ('Electronic Circus', '37i9dQZF1DWVCHIm2MEeIy', 'N/A'),
                 ('Club Beats', '37i9dQZF1DXbX3zSzB4MO0', 'Germany'),
                 ('Wochenende', '37i9dQZF1DX5wcoyvtNnP4', 'Germany'),
                 ('Fit mit Beat', '37i9dQZF1DX5FlZmJ3JWL1', 'Germany'),
                 ('Electro Chill', '37i9dQZF1DX9ND1QF5hZNF', 'France'),
                 ('Motivation pour le sport', '37i9dQZF1DX39mId53VASc', 'France'),
                 ('Lowkey Tech', '37i9dQZF1DX0r3x8OtiwEM', 'N/A'),
                 ('Electronic Rising', '37i9dQZF1DX8AliSIsGeKd', 'Germany'),
                 ('Organica', '37i9dQZF1DX2pprEpa9URZ', 'N/A'),
                 ('Just Chill', '37i9dQZF1DX0FJ8JYkqiJu', 'N/A'),
                 ('Maximum', '37i9dQZF1DX5wB72P2sVsT', 'France'),
                 ('Running UK', '37i9dQZF1DWZ2xRu8ajLOe', 'United Kingdom'),
                 ('Friday Cratediggers', '37i9dQZF1DXa41CMuUARjl', 'N/A'),
                 ('mint Canada', '37i9dQZF1DXdIpacQDPDV5', 'Canada'),
                 ('360 Dance', '37i9dQZF1DWTwCImwcYjDL', 'Netherlands'),
                 ('Groove Theory', '37i9dQZF1DX1tW4VlEfDSS', 'N/A'),
                 ('Friday Funday', '37i9dQZF1DX2Psgy8H1wu7', 'N/A'),
                 ('House is a Feeling', '37i9dQZF1DWXDvpUgU6QYl', 'N/A'),
                 ('Pepplatar till traningspasset', '37i9dQZF1DX7CB1M7sBt21', 'Sweden'),
                 ('Traning', '37i9dQZF1DX4TXm6C4J2mM', 'Sweden'),
                 ('Bass Explosion', '37i9dQZF1DX9Bom9R0tCgx', 'Denmark')]

popIds = [('Todays Top Hits', '37i9dQZF1DXcBWIGoYBM5M', 'N/A'),
          ('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
          ('mint', '37i9dQZF1DX4dyzvuaRJ0n', 'United States'),
          ('Chill Hits', '37i9dQZF1DX4WYpdgoIcn6', 'United States'),
          ('Happy Hits!', '37i9dQZF1DXdPec7aLTmlC', 'United States'),
          ('Mood Booster', '37i9dQZF1DX3rxVfibe1L0', 'United States'),
          ('Teen Party', '37i9dQZF1DX1N5uK98ms5p', 'United States'),
          ('Love Pop', '37i9dQZF1DX50QitC6Oqtn', 'United States'),
          ('Pop Remix', '37i9dQZF1DXcZDD7cfEKhW', 'United States'),
          ('Confidence Boost', '37i9dQZF1DX4fpCWaHOned', 'United States'),
          ('Pop Up', '37i9dQZF1DX6aTaZa0K6VA', 'Brazil'),
          ('Broken Heart', '37i9dQZF1DXbrUpGvoi3TS', 'United States'),
          ('Cardio', '37i9dQZF1DWSJHnPb1f0X3', 'United States'),
          ('Young Wild Free', '37i9dQZF1DX843Qf4lrFtZ', 'N/A'),
          ('Hot Hits UK', '37i9dQZF1DWY4lFlS4Pnso', 'United Kingdom'),
          ('Its a Hit!', '37i9dQZF1DWT1y71ZcMPe5', 'N/A'),
          ('Top Hits Deutschland', '37i9dQZF1DX4jP4eebSWR9', 'Germany'),
          ('Girls Night', '37i9dQZF1DX0Uv9tZ47pWo', 'N/A'),
          ('Pop Rising', '37i9dQZF1DWUa8ZRTfalHk', 'United States'),
          ('TGIF', '37i9dQZF1DXcRXFNfZr7Tp', 'United States'),
          ('Warm Fuzzy Feeling', '37i9dQZF1DX5IDTimEWoTd', 'N/A'),
          ('Hits du Moment', '37i9dQZF1DWVuV87wUBNwc', 'France'),
          ('Daily Lift', '37i9dQZF1DWU13kKnk03AP', 'United States'),
          ('Weekend Hangouts', '37i9dQZF1DXdsy92d7BLpC', 'N/A'),
          ('Wake Up Happy', '37i9dQZF1DX0UrRvztWcAU', 'N/A'),
          ('Hot Hits Australia', '37i9dQZF1DWXXs9GFYnvLB', 'Australia'),
          ('Dinner with Friends', '37i9dQZF1DX4xuWVBs4FgJ', 'N/A'),
          ('Chillax Ka Muna!', '37i9dQZF1DXdUK9FmHZruQ', 'Philippines'),
          ('Partyhymnen', '37i9dQZF1DX9EM98aZosoy', 'Germany'),
          ('Sad Songs', '37i9dQZF1DX7qK8ma5wgG1', 'United Kingdom'),
          ('Stimmungsmacher', '37i9dQZF1DX3Ebqev5IkYU', 'Germany'),
          ('Indie Pop', '37i9dQZF1DWWEcRhUVtL8n', 'United States'),
          ('Top Hits Indonesia', '37i9dQZF1DXa2EiKmMLhFD', 'Indonesia'),
          ('Fresh & Chill', '37i9dQZF1DX5CdVP4rz81C', 'United States'),
          ('Pumped Pop', '37i9dQZF1DX5gQonLbZD9s', 'N/A'),
          ('Pop Right Now', '37i9dQZF1DWVlLVXKTOAYa', 'N/A'),
          ('Fiesta! Fiesta!', '37i9dQZF1DX9KJJbsGEwfj', 'N/A'),
          ('Top Hits NL', '37i9dQZF1DWSBi5svWQ9Nk', 'Netherlands'),
          ('Singled Out', '37i9dQZF1DX8f6LHxMjnzD', 'United States'),
          ('Morning Motivation', '37i9dQZF1DXc5e2bJhV6pu', 'Australia'),
          ('Top Pop', '37i9dQZF1DX92MLsP3K1fI', 'N/A'),
          ('Die Dusch Playlist', '37i9dQZF1DWWh2pBh7dcti', 'Germany'),
          ('De Camino', '37i9dQZF1DXe3a8ZI7Co8I', 'Spain'),
          ('A Perfect Day', '37i9dQZF1DWSXBu5naYCM9', 'N/A'),
          ('The Pop List', '37i9dQZF1DWSVtp02hITpN', 'United Kingdom'),
          ('Hot Hits Canada', '37i9dQZF1DWXT8uSSn6PRy', 'Canada'),
          ('Verao Forever', '37i9dQZF1DWVxZllbpuwRi', 'Brazil'),
          ('Monday Motivation', '37i9dQZF1DX1OY2Lp0bIPp', 'United Kingdom'),
          ('Out Now', '37i9dQZF1DX3LyU0mhfqgP', 'N/A'),
          ('Its Hits Sweden', '37i9dQZF1DWTMYgB8TqtmR', 'Sweden'),
          ('Swag!', '37i9dQZF1DX2YSAZIuAiB1', 'Germany'),
          ('Top of the Morning', '37i9dQZF1DWSWyJydK4fTU', 'N/A'),
          ('Front Left', '37i9dQZF1DX5WTH49Vcnqp', 'Australia'),
          ('Pop Sauce', '37i9dQZF1DXaPCIWxzZwR1', 'N/A'),
          ('La vie est belle', '37i9dQZF1DXdrln2UyZD7F', 'N/A'),
          ('Pulando da Cama', '37i9dQZF1DXa4ss91ghMY4', 'Brazil'),
          ('All New All Now', '37i9dQZF1DX8vwRmUsEIMT', 'United Kingdom'),
          ('Pop Internacional', '37i9dQZF1DX1ngEVM0lKrb', 'Brazil'),
          ('Hitradio', '37i9dQZF1DX274mITVX0K3', 'Germany'),
          ('Garde la peche', '37i9dQZF1DX8685vIIepKh', 'N/A'),
          ('Pop Brandneu', '37i9dQZF1DX1WhyP6stXXl', 'Germany'),
          ('Study Zone', '37i9dQZF1DWSSrwtip3vZP', 'N/A'),
          ('Its Hits Norway', '37i9dQZF1DWUJF24WXSSyO', 'Norway'),
          ('Winter 20', '37i9dQZF1DXcx1szy2g67M', 'Netherlands'),
          ('Just Good Music', '37i9dQZF1DX0b1hHYQtJjp', 'N/A'),
          ('Pop All Day', '37i9dQZF1DXarRysLJmuju', 'N/A'),
          ('Happy Pop Hits', '37i9dQZF1DWVlYsZJXqdym', 'United Kingdom'),
          ('Easy', '37i9dQZF1DX2czWA9hqErK', 'United Kingdom'),
          ('Powerwalk', '37i9dQZF1DX9BXb6GsGCLl', 'N/A'),
          ('Mellow Pop', '37i9dQZF1DWYp3yzk1civi', 'United Kingdom'),
          ('Global X', '37i9dQZF1DWUxHPh2rEiHr', 'N/A'),
          ('Good Times', '37i9dQZF1DWT9NTMXOEmdE', 'N/A'),
          ('Study Break', '37i9dQZF1DX1dvMSwf27JO', 'N/A'),
          ('Pop Study', '37i9dQZF1DWSoyxGghlqv5', 'Turkey'),
          ('E Hit', '37i9dQZF1DX03VbhoH7arm', 'Brazil'),
          ('Chilled Hits', '37i9dQZF1DWVYHdtUb7Wil', 'N/A'),
          ('Happy Pop', '37i9dQZF1DX1H4LbvY4OJi', 'N/A'),
          ('Contemporary Blend', '37i9dQZF1DWViBxWcYEI1b', 'United States'),
          ('Travailler en musique', '37i9dQZF1DXbsWQD03AVcA', 'N/A'),
          ('Top Hits Malaysia', '37i9dQZF1DWWuGaVZsglfu', 'Malaysia'),
          ('Yabanci Pop', '37i9dQZF1DX5cc7vmfioLh', 'Turkey'),
          ('Teen Spirit', '37i9dQZF1DX5drguwUcl5X', 'N/A'),
          ('Caffe del Buongiorno', '37i9dQZF1DX7P3Ec4TfanK', 'Italy'),
          ('Operazione Buonumore', '37i9dQZF1DWTpgpHHF8zH5', 'Italy'),
          ('Directo a Clase', '37i9dQZF1DX8AIVXYufnam', 'N/A'),
          ('Sous la douche', '37i9dQZF1DWUMDyKd0qQIL', 'N/A'),
          ('Its Hits Denmark', '37i9dQZF1DX60OAKjsWlA2', 'Denmark'),
          ('No Stress', '37i9dQZF1DXc0aozDLZsk7', 'N/A'),
          ('Trending Tracks', '37i9dQZF1DXe3Jzj3uus9u', 'N/A'),
          ('Temazos Chill', '37i9dQZF1DWV1PBrIG2weG', 'N/A'),
          ('Sad Bops', '37i9dQZF1DWZUAeYvs88zc', 'N/A'),
          ('BAE', '37i9dQZF1DX1aA8os1ylFZ', 'Netherlands'),
          ('Get Popped!', '37i9dQZF1DXboDblu798Pk', 'Australia'),
          ('Trajet en musique', '37i9dQZF1DX0kTAtGzLyfz', 'France'),
          ('Chilled Pop Hits', '37i9dQZF1DX1IeqVkK7Ebc', 'United Kingdom'),
          ('Sunday Stroll', '37i9dQZF1DWSSBwgXMlrMk', 'N/A'),
          ('New Music Now', '37i9dQZF1DXbpmT3HUTsZm', 'Canada'),
          ('Friozinho', '37i9dQZF1DX6e81LupkkgG', 'Brazil'),
          ('Tarea Casual', '37i9dQZF1DX0yN5997BIDH', 'Mexico'),
          ('Friday Funday', '37i9dQZF1DX2Psgy8H1wu7', 'N/A'),
          ('Happy Hour', '37i9dQZF1DWZ72qOlbizxi', 'Brazil'),
          ('We Be Vibin', '37i9dQZF1DX9TriA5Rm2k8', 'Australia'),
          ('Workout Hits', '37i9dQZF1DWVciwe52Zt0R', 'Denmark'),
          ('Get Your Hits Together', '37i9dQZF1DXc4CrXgl8cum', 'Sweden'),
          ('Hits Dont Lie', '37i9dQZF1DX2iUp2zRnhtp', 'Norway'),
          ('Nouveautes Pop', '37i9dQZF1DWUSKuTscFFGY', 'Germany'),
          ('Lazy Sunday', '37i9dQZF1DWTc452KG008d', 'N/A'),
          ('Top Hits Portugal', '37i9dQZF1DX0rV7skaITBo', 'Portugal'),
          ('Gentle Acoustic', '37i9dQZF1DXdxjdZwLamNx', 'Australia'),
          ('Winter Sounds', '37i9dQZF1DX4H7FFUM2osB', 'N/A'),
          ('Futurs Hits', '37i9dQZF1DWUI9wBgUr4BH', 'N/A'),
          ('Indie Pop Chillout', '37i9dQZF1DX5y8xoSWyhcz', 'N/A'),
          ('Top Hits Singapore', '37i9dQZF1DXdEF3AqJpXE3', 'Singapore'),
          ('Hot Hits New Zealand', '37i9dQZF1DWY5Nosj13GLt', 'New Zealand'),
          ('Top Hits Japan', '37i9dQZF1DXayDMsJG9ZBv', 'Japan'),
          ('Brekkie Time', '37i9dQZF1DWXJGulibxRbg', 'Australia')]

countryIds = [('Hot Country', '37i9dQZF1DX1lVhptIYRda', 'United States'),
              ('Country Kind of Love', '37i9dQZF1DX8WMG8VPSOJC', 'United States'),
              ('New Boots', '37i9dQZF1DX8S0uQvJ4gaa', 'United States'),
              ('All About Country', '37i9dQZF1DWSK8os4XIQBk', 'Canada'),
              ('Nashvilles Worldwide Hot 50', '37i9dQZF1DX7aUUBCKwo4Y', 'United States'),
              ('Texas Music Now', '37i9dQZF1DX3Ee0ngF5ZVQ', 'United States'),
              ('Country Rocks', '37i9dQZF1DWWH0izG4erma', 'N/A'),
              ('Women of Country', '37i9dQZF1DX49poIUZYXp7', 'United States'),
              ('Country Drive', '37i9dQZF1DXdfhOsjRMISB', 'N/A'),
              ('Fresh Country', '37i9dQZF1DWXepGEFFmQXJ', 'Australia'),
              ('New Traditions Country Heroes', '37i9dQZF1DX24Kh15JFQJ0', 'N/A'),
              ('Big Country', '37i9dQZF1DXaJXCbmtHVHV', 'N/A'),
              ('Breakout Country', '37i9dQZF1DWW7RgkOJG32Y', 'N/A'),
              ('Country Favourites', '37i9dQZF1DX13ZzXoot6Jc', 'Canada'),
              ('Very Nearly Nashville', '37i9dQZF1DWXU4C3nPzApC', 'United Kingdom'),
              ('Still Hot', '37i9dQZF1DX6rVyqO2FaN8', 'N/A'),
              ('PopCo', '37i9dQZF1DXadasIcsfbqh', 'United States'),
              ('Nashville Stripped', '37i9dQZF1DX2ViysbCzMHO', 'N/A'),
              ('Next From Nashville', '37i9dQZF1DX0bUGQdz5BJG', 'United States'),
              ('Live Country', '37i9dQZF1DWYV2Gh2QglGo', 'Canada'),
              ('New Music Nashville', '37i9dQZF1DWVn8zvR5ROMB', 'N/A')]

rnbIds = [('Are & Be', '37i9dQZF1DX4SBhb3fqCJd', 'United States'),
          ('Chilled R&B', '37i9dQZF1DX2UgsUIg75Vg', 'United States'),
          ('Bedroom Jams', '37i9dQZF1DX0QKpU3cGsyb', 'Netherlands'),
          ('POLLEN', '37i9dQZF1DWWBHeXOYZf74', 'N/A'),
          ('Alternative R&B', '37i9dQZF1DWSfMe9z89s9B', 'United States'),
          ('Amplify', '37i9dQZF1DWU8quswnFt3c', 'N/A'),
          ('The Newness', '37i9dQZF1DWUzFXarNiofw', 'United States'),
          ('Fresh Finds', '37i9dQZF1DWWjGdmeTyeJ6', 'United States'),
          ('Soul Lounge', '37i9dQZF1DX62Nfha2yFhL', 'N/A'),
          ('This Is How We Do', '37i9dQZF1DX4a0nQYnltiQ', 'N/A'),
          ('Butter', '37i9dQZF1DWVzZlRWgqAGH', 'United States'),
          ('Soul Coffee', '37i9dQZF1DXaXDsfv6nvZ5', 'N/A'),
          ('Sweet Soul Sunday', '37i9dQZF1DX7QC1DnNqj3m', 'United Kingdom'),
          ('Black Girl Magic', '37i9dQZF1DX4ezQVslkJiT', 'N/A'),
          ('All Funked Up', '37i9dQZF1DX4WgZiuR77Ef', 'N/A'),
          ('Study Break', '37i9dQZF1DX1dvMSwf27JO', 'N/A'),
          ('Silk Sheets', '37i9dQZF1DWVGy1YP1ojM5', 'United States'),
          ('Soul n the City', '37i9dQZF1DWSXWSaQmvWOB', 'Netherlands'),
          ('Spotify & Chill', '37i9dQZF1DX7ZnTv0GKubq', 'United Kingdom'),
          ('Arkada Calsin', '37i9dQZF1DXcy0AaElSqwE', 'Turkey'),
          ('Good Morning Jazz', '37i9dQZF1DX71VcjjnyaBQ', 'N/A'),
          ('Next Wave Neo Soul', '37i9dQZF1DX44dZ4p5QLf4', 'South Africa'),
          ('Ready for the Day', '37i9dQZF1DX6Rl8uES4jYu', 'N/A'),
          ('Retro Pop', '37i9dQZF1DXcTieYAg7jq1', 'N/A'),
          ('Your Office Stereo', '37i9dQZF1DX31KQt69Gaqf', 'United Kingdom'),
          ('Soultronic', '37i9dQZF1DXdc0DUqaW3MZ', 'United Kingdom'),
          ('9PM', '37i9dQZF1DX6KOz8PNkOlS', 'N/A'),
          ('Chill Mode On', '37i9dQZF1DX9FcC8tuoPzi', 'Netherlands'),
          ('R&B Feels', '37i9dQZF1DX6GYkg76TRV8', 'N/A'),
          ('R&B UK', '37i9dQZF1DX942d1NzGgzk', 'United Kingdom')]


allIds = [('Are & Be', '37i9dQZF1DX4SBhb3fqCJd', 'United States'),
          ('Chilled R&B', '37i9dQZF1DX2UgsUIg75Vg', 'United States'),
          ('Bedroom Jams', '37i9dQZF1DX0QKpU3cGsyb', 'Netherlands'),
          ('POLLEN', '37i9dQZF1DWWBHeXOYZf74', 'N/A'),
          ('Alternative R&B', '37i9dQZF1DWSfMe9z89s9B', 'United States'),
          ('Amplify', '37i9dQZF1DWU8quswnFt3c', 'N/A'),
          ('The Newness', '37i9dQZF1DWUzFXarNiofw', 'United States'),
          ('Fresh Finds', '37i9dQZF1DWWjGdmeTyeJ6', 'United States'),
          ('Soul Lounge', '37i9dQZF1DX62Nfha2yFhL', 'N/A'),
          ('This Is How We Do', '37i9dQZF1DX4a0nQYnltiQ', 'N/A'),
          ('Butter', '37i9dQZF1DWVzZlRWgqAGH', 'United States'),
          ('Soul Coffee', '37i9dQZF1DXaXDsfv6nvZ5', 'N/A'),
          ('Sweet Soul Sunday', '37i9dQZF1DX7QC1DnNqj3m', 'United Kingdom'),
          ('Black Girl Magic', '37i9dQZF1DX4ezQVslkJiT', 'N/A'),
          ('All Funked Up', '37i9dQZF1DX4WgZiuR77Ef', 'N/A'),
          ('Study Break', '37i9dQZF1DX1dvMSwf27JO', 'N/A'),
          ('Silk Sheets', '37i9dQZF1DWVGy1YP1ojM5', 'United States'),
          ('Soul n the City', '37i9dQZF1DWSXWSaQmvWOB', 'Netherlands'),
          ('Spotify & Chill', '37i9dQZF1DX7ZnTv0GKubq', 'United Kingdom'),
          ('Arkada Calsin', '37i9dQZF1DXcy0AaElSqwE', 'Turkey'),
          ('Good Morning Jazz', '37i9dQZF1DX71VcjjnyaBQ', 'N/A'),
          ('Next Wave Neo Soul', '37i9dQZF1DX44dZ4p5QLf4', 'South Africa'),
          ('Ready for the Day', '37i9dQZF1DX6Rl8uES4jYu', 'N/A'),
          ('Retro Pop', '37i9dQZF1DXcTieYAg7jq1', 'N/A'),
          ('Your Office Stereo', '37i9dQZF1DX31KQt69Gaqf', 'United Kingdom'),
          ('Soultronic', '37i9dQZF1DXdc0DUqaW3MZ', 'United Kingdom'),
          ('9PM', '37i9dQZF1DX6KOz8PNkOlS', 'N/A'),
          ('Chill Mode On', '37i9dQZF1DX9FcC8tuoPzi', 'Netherlands'),
          ('R&B Feels', '37i9dQZF1DX6GYkg76TRV8', 'N/A'),
          ('R&B UK', '37i9dQZF1DX942d1NzGgzk', 'United Kingdom'),
          ('Hot Country', '37i9dQZF1DX1lVhptIYRda', 'United States'),
          ('Country Kind of Love', '37i9dQZF1DX8WMG8VPSOJC', 'United States'),
          ('New Boots', '37i9dQZF1DX8S0uQvJ4gaa', 'United States'),
          ('All About Country', '37i9dQZF1DWSK8os4XIQBk', 'Canada'),
          ('Nashvilles Worldwide Hot 50', '37i9dQZF1DX7aUUBCKwo4Y', 'United States'),
          ('Texas Music Now', '37i9dQZF1DX3Ee0ngF5ZVQ', 'United States'),
          ('Country Rocks', '37i9dQZF1DWWH0izG4erma', 'N/A'),
          ('Women of Country', '37i9dQZF1DX49poIUZYXp7', 'United States'),
          ('Country Drive', '37i9dQZF1DXdfhOsjRMISB', 'N/A'),
          ('Fresh Country', '37i9dQZF1DWXepGEFFmQXJ', 'Australia'),
          ('New Traditions Country Heroes', '37i9dQZF1DX24Kh15JFQJ0', 'N/A'),
          ('Big Country', '37i9dQZF1DXaJXCbmtHVHV', 'N/A'),
          ('Breakout Country', '37i9dQZF1DWW7RgkOJG32Y', 'N/A'),
          ('Country Favourites', '37i9dQZF1DX13ZzXoot6Jc', 'Canada'),
          ('Very Nearly Nashville', '37i9dQZF1DWXU4C3nPzApC', 'United Kingdom'),
          ('Still Hot', '37i9dQZF1DX6rVyqO2FaN8', 'N/A'),
          ('PopCo', '37i9dQZF1DXadasIcsfbqh', 'United States'),
          ('Nashville Stripped', '37i9dQZF1DX2ViysbCzMHO', 'N/A'),
          ('Next From Nashville', '37i9dQZF1DX0bUGQdz5BJG', 'United States'),
          ('Live Country', '37i9dQZF1DWYV2Gh2QglGo', 'Canada'),
          ('New Music Nashville', '37i9dQZF1DWVn8zvR5ROMB', 'N/A'),
          ('Todays Top Hits', '37i9dQZF1DXcBWIGoYBM5M', 'N/A'),
          ('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
          ('mint', '37i9dQZF1DX4dyzvuaRJ0n', 'United States'),
          ('Chill Hits', '37i9dQZF1DX4WYpdgoIcn6', 'United States'),
          ('Happy Hits!', '37i9dQZF1DXdPec7aLTmlC', 'United States'),
          ('Mood Booster', '37i9dQZF1DX3rxVfibe1L0', 'United States'),
          ('Teen Party', '37i9dQZF1DX1N5uK98ms5p', 'United States'),
          ('Love Pop', '37i9dQZF1DX50QitC6Oqtn', 'United States'),
          ('Pop Remix', '37i9dQZF1DXcZDD7cfEKhW', 'United States'),
          ('Confidence Boost', '37i9dQZF1DX4fpCWaHOned', 'United States'),
          ('Pop Up', '37i9dQZF1DX6aTaZa0K6VA', 'Brazil'),
          ('Broken Heart', '37i9dQZF1DXbrUpGvoi3TS', 'United States'),
          ('Cardio', '37i9dQZF1DWSJHnPb1f0X3', 'United States'),
          ('Young Wild Free', '37i9dQZF1DX843Qf4lrFtZ', 'N/A'),
          ('Hot Hits UK', '37i9dQZF1DWY4lFlS4Pnso', 'United Kingdom'),
          ('Its a Hit!', '37i9dQZF1DWT1y71ZcMPe5', 'N/A'),
          ('Top Hits Deutschland', '37i9dQZF1DX4jP4eebSWR9', 'Germany'),
          ('Girls Night', '37i9dQZF1DX0Uv9tZ47pWo', 'N/A'),
          ('Pop Rising', '37i9dQZF1DWUa8ZRTfalHk', 'United States'),
          ('TGIF', '37i9dQZF1DXcRXFNfZr7Tp', 'United States'),
          ('Warm Fuzzy Feeling', '37i9dQZF1DX5IDTimEWoTd', 'N/A'),
          ('Hits du Moment', '37i9dQZF1DWVuV87wUBNwc', 'France'),
          ('Daily Lift', '37i9dQZF1DWU13kKnk03AP', 'United States'),
          ('Weekend Hangouts', '37i9dQZF1DXdsy92d7BLpC', 'N/A'),
          ('Wake Up Happy', '37i9dQZF1DX0UrRvztWcAU', 'N/A'),
          ('Hot Hits Australia', '37i9dQZF1DWXXs9GFYnvLB', 'Australia'),
          ('Dinner with Friends', '37i9dQZF1DX4xuWVBs4FgJ', 'N/A'),
          ('Chillax Ka Muna!', '37i9dQZF1DXdUK9FmHZruQ', 'Philippines'),
          ('Partyhymnen', '37i9dQZF1DX9EM98aZosoy', 'Germany'),
          ('Sad Songs', '37i9dQZF1DX7qK8ma5wgG1', 'United Kingdom'),
          ('Stimmungsmacher', '37i9dQZF1DX3Ebqev5IkYU', 'Germany'),
          ('Indie Pop', '37i9dQZF1DWWEcRhUVtL8n', 'United States'),
          ('Top Hits Indonesia', '37i9dQZF1DXa2EiKmMLhFD', 'Indonesia'),
          ('Fresh & Chill', '37i9dQZF1DX5CdVP4rz81C', 'United States'),
          ('Pumped Pop', '37i9dQZF1DX5gQonLbZD9s', 'N/A'),
          ('Pop Right Now', '37i9dQZF1DWVlLVXKTOAYa', 'N/A'),
          ('Fiesta! Fiesta!', '37i9dQZF1DX9KJJbsGEwfj', 'N/A'),
          ('Top Hits NL', '37i9dQZF1DWSBi5svWQ9Nk', 'Netherlands'),
          ('Singled Out', '37i9dQZF1DX8f6LHxMjnzD', 'United States'),
          ('Morning Motivation', '37i9dQZF1DXc5e2bJhV6pu', 'Australia'),
          ('Top Pop', '37i9dQZF1DX92MLsP3K1fI', 'N/A'),
          ('Die Dusch Playlist', '37i9dQZF1DWWh2pBh7dcti', 'Germany'),
          ('De Camino', '37i9dQZF1DXe3a8ZI7Co8I', 'Spain'),
          ('A Perfect Day', '37i9dQZF1DWSXBu5naYCM9', 'N/A'),
          ('The Pop List', '37i9dQZF1DWSVtp02hITpN', 'United Kingdom'),
          ('Hot Hits Canada', '37i9dQZF1DWXT8uSSn6PRy', 'Canada'),
          ('Verao Forever', '37i9dQZF1DWVxZllbpuwRi', 'Brazil'),
          ('Monday Motivation', '37i9dQZF1DX1OY2Lp0bIPp', 'United Kingdom'),
          ('Out Now', '37i9dQZF1DX3LyU0mhfqgP', 'N/A'),
          ('Its Hits Sweden', '37i9dQZF1DWTMYgB8TqtmR', 'Sweden'),
          ('Swag!', '37i9dQZF1DX2YSAZIuAiB1', 'Germany'),
          ('Top of the Morning', '37i9dQZF1DWSWyJydK4fTU', 'N/A'),
          ('Front Left', '37i9dQZF1DX5WTH49Vcnqp', 'Australia'),
          ('Pop Sauce', '37i9dQZF1DXaPCIWxzZwR1', 'N/A'),
          ('La vie est belle', '37i9dQZF1DXdrln2UyZD7F', 'N/A'),
          ('Pulando da Cama', '37i9dQZF1DXa4ss91ghMY4', 'Brazil'),
          ('All New All Now', '37i9dQZF1DX8vwRmUsEIMT', 'United Kingdom'),
          ('Pop Internacional', '37i9dQZF1DX1ngEVM0lKrb', 'Brazil'),
          ('Hitradio', '37i9dQZF1DX274mITVX0K3', 'Germany'),
          ('Garde la peche', '37i9dQZF1DX8685vIIepKh', 'N/A'),
          ('Pop Brandneu', '37i9dQZF1DX1WhyP6stXXl', 'Germany'),
          ('Study Zone', '37i9dQZF1DWSSrwtip3vZP', 'N/A'),
          ('Its Hits Norway', '37i9dQZF1DWUJF24WXSSyO', 'Norway'),
          ('Winter 20', '37i9dQZF1DXcx1szy2g67M', 'Netherlands'),
          ('Just Good Music', '37i9dQZF1DX0b1hHYQtJjp', 'N/A'),
          ('Pop All Day', '37i9dQZF1DXarRysLJmuju', 'N/A'),
          ('Happy Pop Hits', '37i9dQZF1DWVlYsZJXqdym', 'United Kingdom'),
          ('Easy', '37i9dQZF1DX2czWA9hqErK', 'United Kingdom'),
          ('Powerwalk', '37i9dQZF1DX9BXb6GsGCLl', 'N/A'),
          ('Mellow Pop', '37i9dQZF1DWYp3yzk1civi', 'United Kingdom'),
          ('Global X', '37i9dQZF1DWUxHPh2rEiHr', 'N/A'),
          ('Good Times', '37i9dQZF1DWT9NTMXOEmdE', 'N/A'),
          ('Study Break', '37i9dQZF1DX1dvMSwf27JO', 'N/A'),
          ('Pop Study', '37i9dQZF1DWSoyxGghlqv5', 'Turkey'),
          ('E Hit', '37i9dQZF1DX03VbhoH7arm', 'Brazil'),
          ('Chilled Hits', '37i9dQZF1DWVYHdtUb7Wil', 'N/A'),
          ('Happy Pop', '37i9dQZF1DX1H4LbvY4OJi', 'N/A'),
          ('Contemporary Blend', '37i9dQZF1DWViBxWcYEI1b', 'United States'),
          ('Travailler en musique', '37i9dQZF1DXbsWQD03AVcA', 'N/A'),
          ('Top Hits Malaysia', '37i9dQZF1DWWuGaVZsglfu', 'Malaysia'),
          ('Yabanci Pop', '37i9dQZF1DX5cc7vmfioLh', 'Turkey'),
          ('Teen Spirit', '37i9dQZF1DX5drguwUcl5X', 'N/A'),
          ('Caffe del Buongiorno', '37i9dQZF1DX7P3Ec4TfanK', 'Italy'),
          ('Operazione Buonumore', '37i9dQZF1DWTpgpHHF8zH5', 'Italy'),
          ('Directo a Clase', '37i9dQZF1DX8AIVXYufnam', 'N/A'),
          ('Sous la douche', '37i9dQZF1DWUMDyKd0qQIL', 'N/A'),
          ('Its Hits Denmark', '37i9dQZF1DX60OAKjsWlA2', 'Denmark'),
          ('No Stress', '37i9dQZF1DXc0aozDLZsk7', 'N/A'),
          ('Trending Tracks', '37i9dQZF1DXe3Jzj3uus9u', 'N/A'),
          ('Temazos Chill', '37i9dQZF1DWV1PBrIG2weG', 'N/A'),
          ('Sad Bops', '37i9dQZF1DWZUAeYvs88zc', 'N/A'),
          ('BAE', '37i9dQZF1DX1aA8os1ylFZ', 'Netherlands'),
          ('Get Popped!', '37i9dQZF1DXboDblu798Pk', 'Australia'),
          ('Trajet en musique', '37i9dQZF1DX0kTAtGzLyfz', 'France'),
          ('Chilled Pop Hits', '37i9dQZF1DX1IeqVkK7Ebc', 'United Kingdom'),
          ('Sunday Stroll', '37i9dQZF1DWSSBwgXMlrMk', 'N/A'),
          ('New Music Now', '37i9dQZF1DXbpmT3HUTsZm', 'Canada'),
          ('Friozinho', '37i9dQZF1DX6e81LupkkgG', 'Brazil'),
          ('Tarea Casual', '37i9dQZF1DX0yN5997BIDH', 'Mexico'),
          ('Friday Funday', '37i9dQZF1DX2Psgy8H1wu7', 'N/A'),
          ('Happy Hour', '37i9dQZF1DWZ72qOlbizxi', 'Brazil'),
          ('We Be Vibin', '37i9dQZF1DX9TriA5Rm2k8', 'Australia'),
          ('Workout Hits', '37i9dQZF1DWVciwe52Zt0R', 'Denmark'),
          ('Get Your Hits Together', '37i9dQZF1DXc4CrXgl8cum', 'Sweden'),
          ('Hits Dont Lie', '37i9dQZF1DX2iUp2zRnhtp', 'Norway'),
          ('Nouveautes Pop', '37i9dQZF1DWUSKuTscFFGY', 'Germany'),
          ('Lazy Sunday', '37i9dQZF1DWTc452KG008d', 'N/A'),
          ('Top Hits Portugal', '37i9dQZF1DX0rV7skaITBo', 'Portugal'),
          ('Gentle Acoustic', '37i9dQZF1DXdxjdZwLamNx', 'Australia'),
          ('Winter Sounds', '37i9dQZF1DX4H7FFUM2osB', 'N/A'),
          ('Futurs Hits', '37i9dQZF1DWUI9wBgUr4BH', 'N/A'),
          ('Indie Pop Chillout', '37i9dQZF1DX5y8xoSWyhcz', 'N/A'),
          ('Top Hits Singapore', '37i9dQZF1DXdEF3AqJpXE3', 'Singapore'),
          ('Hot Hits New Zealand', '37i9dQZF1DWY5Nosj13GLt', 'New Zealand'),
          ('Top Hits Japan', '37i9dQZF1DXayDMsJG9ZBv', 'Japan'),
          ('Brekkie Time', '37i9dQZF1DWXJGulibxRbg', 'Australia'),
          ('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
          ('mint', '37i9dQZF1DX4dyzvuaRJ0n', 'United States'),
          ('Motivation Mix', '37i9dQZF1DXdxcBWuJkbcy', 'United States'),
          ('Dance Party', '37i9dQZF1DXaXB8fQg7xif', 'N/A'),
          ('Dance Hits', '37i9dQZF1DX0BcQWzuB7ZO', 'United States'),
          ('Cardio', '37i9dQZF1DWSJHnPb1f0X3', 'United States'),
          ('Dance Rising', '37i9dQZF1DX8tZsk68tuDw', 'United States'),
          ('Power Hour', '37i9dQZF1DX32NsLKyzScr', 'N/A'),
          ('Lounge Soft House', '37i9dQZF1DX82pCGH5USnM', 'N/A'),
          ('Main Stage', '37i9dQZF1DX7ZUug1ANKRP', 'Germany'),
          ('Techno Bunker', '37i9dQZF1DX6J5NfMJS675', 'N/A'),
          ('Wake Up Happy', '37i9dQZF1DX0UrRvztWcAU', 'N/A'),
          ('Young & Free', '37i9dQZF1DXca8AyWK6Y7g', 'United States'),
          ('Chillout Lounge', '37i9dQZF1DWTvNyxOwkztu', 'Germany'),
          ('Happy Beats', '37i9dQZF1DWSf2RDTDayIx', 'N/A'),
          ('Massive Dance Hits', '37i9dQZF1DX5uokaTN4FTR', 'N/A'),
          ('Partyhymnen', '37i9dQZF1DX9EM98aZosoy', 'Germany'),
          ('Stimmungsmacher', '37i9dQZF1DX3Ebqev5IkYU', 'Germany'),
          ('You Can Do It', '37i9dQZF1DX1gcrZ1xC96D', 'N/A'),
          ('Night Rider', '37i9dQZF1DX6GJXiuZRisr', 'N/A'),
          ('Happy Dance', '37i9dQZF1DX4uPi2roRUwU', 'N/A'),
          ('Heart Beats', '37i9dQZF1DWSRc3WJklgBs', 'N/A'),
          ('UK House Music', '37i9dQZF1DWSrVdvTl1tVY', 'United Kingdom'),
          ('Bass Arcade', '37i9dQZF1DX0hvSv9Rf41p', 'N/A'),
          ('All Night Dance Party', '37i9dQZF1DX0MXH7aN4Pxn', 'N/A'),
          ('Metropolis', '37i9dQZF1DX8CopunbDxgW', 'N/A'),
          ('Impulso Creativo', '37i9dQZF1DWWnMZKMl7SWB', 'Spain'),
          ('Workout Beats', '37i9dQZF1DWUSyphfcc6aL', 'Australia'),
          ('Electronic Circus', '37i9dQZF1DWVCHIm2MEeIy', 'N/A'),
          ('Club Beats', '37i9dQZF1DXbX3zSzB4MO0', 'Germany'),
          ('Wochenende', '37i9dQZF1DX5wcoyvtNnP4', 'Germany'),
          ('Fit mit Beat', '37i9dQZF1DX5FlZmJ3JWL1', 'Germany'),
          ('Electro Chill', '37i9dQZF1DX9ND1QF5hZNF', 'France'),
          ('Motivation pour le sport', '37i9dQZF1DX39mId53VASc', 'France'),
          ('Lowkey Tech', '37i9dQZF1DX0r3x8OtiwEM', 'N/A'),
          ('Electronic Rising', '37i9dQZF1DX8AliSIsGeKd', 'Germany'),
          ('Organica', '37i9dQZF1DX2pprEpa9URZ', 'N/A'),
          ('Just Chill', '37i9dQZF1DX0FJ8JYkqiJu', 'N/A'),
          ('Maximum', '37i9dQZF1DX5wB72P2sVsT', 'France'),
          ('Running UK', '37i9dQZF1DWZ2xRu8ajLOe', 'United Kingdom'),
          ('Friday Cratediggers', '37i9dQZF1DXa41CMuUARjl', 'N/A'),
          ('mint Canada', '37i9dQZF1DXdIpacQDPDV5', 'Canada'),
          ('360 Dance', '37i9dQZF1DWTwCImwcYjDL', 'Netherlands'),
          ('Groove Theory', '37i9dQZF1DX1tW4VlEfDSS', 'N/A'),
          ('Friday Funday', '37i9dQZF1DX2Psgy8H1wu7', 'N/A'),
          ('House is a Feeling', '37i9dQZF1DWXDvpUgU6QYl', 'N/A'),
          ('Pepplatar till traningspasset', '37i9dQZF1DX7CB1M7sBt21', 'Sweden'),
          ('Traning', '37i9dQZF1DX4TXm6C4J2mM', 'Sweden'),
          ('Bass Explosion', '37i9dQZF1DX9Bom9R0tCgx', 'Denmark'),
          ('MostBeautifulSongsintheWorld', '37i9dQZF1DX9Z3vMB2b8im', 'United Kingdom'),
          ('Infinite Acoustic', '37i9dQZF1DX6z20IXmBjWI', 'N/A'),
          ('Ultimate Indie', '37i9dQZF1DX2Nc3B70tvx0', 'United States'),
          ('Roots Rising', '37i9dQZF1DWYV7OOaGhoH0', 'N/A'),
          ('Hanging Out and Relaxing', '37i9dQZF1DXci7j0DJQgGp', 'United States'),
          ('Totally Stress Free', '37i9dQZF1DWT7XSlwvR1ar', 'United States'),
          ('Wild and Free', '37i9dQZF1DX5Q5wA1hY6bS', 'United States'),
          ('Young & Free', '37i9dQZF1DXca8AyWK6Y7g', 'United States'),
          ('Indie Pop', '37i9dQZF1DWWEcRhUVtL8n', 'United States'),
          ('All New Indie', '37i9dQZF1DXdbXrPNafg9d', 'United States'),
          ('POLLEN', '37i9dQZF1DWWBHeXOYZf74', 'N/A'),
          ('The New Alt', '37i9dQZF1DX82GYcclJ3Ug', 'United States'),
          ('Fruhlingsgefuhle', '37i9dQZF1DWZESE3fHLhmD', 'Germany'),
          ('Fresh Finds', '37i9dQZF1DWWjGdmeTyeJ6', 'United States'),
          ('Cafe Libros', '37i9dQZF1DWZkMGGysxknj', 'N/A'),
          ('Fresh Folk', '37i9dQZF1DXaUDcU6KDCj4', 'N/A'),
          ('Lorem', '37i9dQZF1DXdwmD5Q7Gxah', 'N/A'),
          ('Front Left', '37i9dQZF1DX5WTH49Vcnqp', 'Australia'),
          ('Fruhlings Chillout', '37i9dQZF1DXaIrEwuQ3hyy', 'Germany'),
          ('Wake Up and Smell the Coffee', '37i9dQZF1DXcxacyAXkQDu', 'Sweden'),
          ('Your Coffee Break', '37i9dQZF1DWYqdkUCLfYzP', 'United Kingdom'),
          ('Its ALT Good!', '37i9dQZF1DX2SK4ytI2KAZ', 'United States'),
          ('Indie Stage', '37i9dQZF1DX1hBl8Jfe9dd', 'Brazil'),
          ('The Stress Buster', '37i9dQZF1DWUvQoIOFMFUT', 'United Kingdom'),
          ('Totally Alt', '37i9dQZF1DXa6YOhGMjjgx', 'United States'),
          ('Rockin Vibes', '37i9dQZF1DX2aneNMeYHQ8', 'N/A'),
          ('Feelgood Indie', '37i9dQZF1DWWM6GBnxtToT', 'Germany'),
          ('OFF POP', '37i9dQZF1DX07Bg0Q5GozA', 'Germany'),
          ('Melancolia Indie', '37i9dQZF1DX4jSp9PHDkEC', 'Mexico'),
          ('The Indie List', '37i9dQZF1DWVTKDs2aOkxu', 'United Kingdom'),
          ('Coffee and Chill', '37i9dQZF1DXa1BeMIGX5Du', 'Australia'),
          ('Akustischer Fruhling', '37i9dQZF1DX8FmtpZigIQk', 'Germany'),
          ('Arkada Calsın', '37i9dQZF1DXcy0AaElSqwE', 'Turkey'),
          ('Apero', '37i9dQZF1DWZk2SPZ3bugX', 'N/A'),
          ('Lost In The Woods', '37i9dQZF1DWYm3dUe8iSaq', 'United Kingdom'),
          ('Gentle Acoustic', '37i9dQZF1DXdxjdZwLamNx', 'Australia'),
          ('Your Office Stereo', '37i9dQZF1DX31KQt69Gaqf', 'United Kingdom'),
          ('Van Life', '37i9dQZF1DX2ogDiL6nZJr', 'N/A'),
          ('RapCaviar', '37i9dQZF1DX0XUsuxWHRQd', 'United States'),
          ('Get Turnt', '37i9dQZF1DWY4xHQp97fN6', 'United States'),
          ('Power Workout', '37i9dQZF1DWUVpAXiEPK8P', 'United States'),
          ('Most Necessary', '37i9dQZF1DX2RxBh64BHjQ', 'United States'),
          ('Hot Rhythmic', '37i9dQZF1DWYs83FtTMQFw', 'United States'),
          ('Love, Sex, & Water', '37i9dQZF1DWX3387IZmjNa', 'United States'),
          ('Signed XOXO', '37i9dQZF1DX2A29LI7xHn1', 'United States'),
          ('Channel X', '37i9dQZF1DX4y8h9WqDPAE', 'United States'),
          ('Workout Twerkout', '37i9dQZF1DX0HRj9P7NxeE', 'United States'),
          ('The Realest Down South', '37i9dQZF1DX0Tkc6ltcBfU', 'United States'),
          ('Singled Out', '37i9dQZF1DX8f6LHxMjnzD', 'United States'),
          ('The Newness', '37i9dQZF1DWUzFXarNiofw', 'United States'),
          ('Mind Right', '37i9dQZF1DX5hR0J49CmXC', 'United States'),
          ('Clout Culture', '37i9dQZF1DWVk7x1ClrO0Y', 'United States'),
          ('Hip-Hop Central', '37i9dQZF1DWY6tYEFs22tT', 'Canada'),
          ('R&B Right Now', '37i9dQZF1DX2WkIBRaChxW', 'Canada'),
          ('New Music Now', '37i9dQZF1DXbpmT3HUTsZm', 'Canada'),
          ('Top Hits Deutschland', '37i9dQZF1DX4jP4eebSWR9', 'Germany'),
          ('Swag!', '37i9dQZF1DX2YSAZIuAiB1', 'Germany'),
          ('Hot Hits Australia', '37i9dQZF1DWXXs9GFYnvLB', 'Australia'),
          ('Urban Flavour', '37i9dQZF1DXa49JU4zzjb9', 'Australia'),
          ('Hot Hits New Zealand', '37i9dQZF1DWY5Nosj13GLt', 'New Zealand'),
          ('Hot Hip Hop', '37i9dQZF1DWVPRVPGc4ZVv', 'France'),
          ('Hot Hits UK', '37i9dQZF1DWY4lFlS4Pnso', 'United Kingdom'),
          ('Rap Workout', '37i9dQZF1DX76t638V6CA8', 'United Kingdom'),
          ('Grime Shutdown', '37i9dQZF1DWSOkubnsDCSS', 'United Kingdom'),
          ('Rap UK', '37i9dQZF1DX6PKX5dyBKeq', 'United Kingdom'),
          ('Who We Be', '37i9dQZF1DXcDoDDetPsEg', 'United Kingdom'),
          ('Alternative Hip Hop', '37i9dQZF1DWTggY0yqBxES', 'United Kingdom'),
          ('Afro Bashment', '37i9dQZF1DXdeMORbC1XNa', 'United Kingdom'),
          ('Bedroom Jams', '37i9dQZF1DX0QKpU3cGsyb', 'Netherlands'),
          ('Mellow Bars', '37i9dQZF1DWT6MhXz0jw61', 'Netherlands'),
          ('Top Hits NL', '37i9dQZF1DWSBi5svWQ9Nk', 'Netherlands'),
          ('Beast Mode', '37i9dQZF1DX76Wlfdnj7AP', 'N/A'),
          ('BAE', '37i9dQZF1DWX3387IZmjNa', 'United States'),
          ('Off The Strength', '37i9dQZF1DXaxIqwkEGFEh', 'N/A'),
          ('Shisha Lounge', '37i9dQZF1DX68x6hand0cN', 'N/A'),
          ('Locked In', '37i9dQZF1DWTl4y3vgJOXW', 'N/A'),
          ('Cali Fire', '37i9dQZF1DWSvKsRPPnv5o', 'United States'),
          ('Hip-Hop Mixtape', '37i9dQZF1DWVdgXTbYm2r0', 'N/A'),
          ('Anti Pop', '37i9dQZF1DWWqNV5cS50j6', 'N/A'),
          ('Spilled Ink', '37i9dQZF1DWSTeI2WWFaia', 'N/A'),
          ('State of Mind', '37i9dQZF1DX1YPTAhwehsC', 'N/A'),
          ('A1 Hip-Hop', '37i9dQZF1DX0sDai2F5jCQ', 'N/A'),
          ('Hip-Hop Favourites', '37i9dQZF1DX48TTZL62Yht', 'N/A'),
          ('Hip-Hop Yoga', '37i9dQZF1DX4FJyIpen2Yf', 'N/A'),
          ('Beats & Rhymes', '37i9dQZF1DXcA6dRp8rwj6', 'N/A'),
          ('Treino Hip-Hop', '37i9dQZF1DX9wPYtCQ8Q0s', 'Brazil'),
          ('Internet People', '37i9dQZF1DX6OgmB2fwLGd', 'N/A'),
          ('Hip Hop Mix', '37i9dQZF1DWXRPjCBAuFj3', 'N/A'),
          ('100', '37i9dQZF1DWXfgo3OOonqa', 'Sweden'),
          ('¡Viva Latino!', '37i9dQZF1DX10zKzsJ2jva', 'N/A'),
          ('Baila Reggaeton', '37i9dQZF1DWY7IeIP1cdjF', 'Argentina'),
          ('Verano Forever', '37i9dQZF1DXdnGF35OawbN', 'Spain'),
          ('Exitos Mexico', '37i9dQZF1DX5BAPG29mHS8', 'Mexico'),
          ('Exitos Espana', '37i9dQZF1DXaxEKcoCdWHD', 'Spain'),
          ('Exitos Argentina', '37i9dQZF1DXbbu94YBG7Ye', 'Argentina'),
          ('United Kingdom Top 50', '37i9dQZEVXbLnolsZ8PSNw', 'United Kingdom'),
          ('Trap Nation', '0NCspsyf0OS4BsPgGhkQXM', 'N/A'),
          ('Exitos USA', '37i9dQZF1DX4oUPBOaEkL6', 'United States'),
          ('Trap Land', '37i9dQZF1DXde9tuMHuIsj', 'N/A'),
          ('Mansion Reggaeton', '37i9dQZF1DWZjqjZMudx9T', 'N/A'),
          ('Modus Mio', '37i9dQZF1DX36edUJpD76c', 'Germany'),
          ('Zumba Beats', '37i9dQZF1DX7cmFV9rWM0u', 'N/A'),
          ('Exitos Chile', '37i9dQZF1DXclgCwbk0uat', 'Chile'),
          ('Radar Latino', '37i9dQZF1DWZoF06RIo9el', 'N/A'),
          ('Deutschrap Brandneu', '37i9dQZF1DWSTqUqJcxFk6', 'Germany'),
          ('Tatak Pinoy', '37i9dQZF1DX0iFfuXuP4Pm', 'Philippines'),
          ('Fuego', '37i9dQZF1DX8sljIJzI0oo', 'N/A'),
          ('Spain Top 50', '37i9dQZEVXbNFJfN1Vw8d9', 'Spain'),
          ('Mexico Top 50', '37i9dQZEVXbO3qyFxbkOE1', 'Mexico'),
          ('Deutschrap Royal', '37i9dQZF1DX4TiN7pMwV0Z', 'N/A'),
          ('Hits Urbanos', '37i9dQZF1DWVskFRGurTfg', 'N/A'),
          ('PVNCHLNRS', '37i9dQZF1DX1X23oiQRTB5', 'France'),
          ('RAPublica', '37i9dQZF1DWSIvbYYt1Dvi', 'Brazil'),
          ('Dancehall Official', '37i9dQZF1DXan38dNVDdl4', 'N/A'),
          ('Viral Latino', '37i9dQZF1DX5y71ufjoyXC', 'N/A'),
          ('Hip Hop Hits', '4ykrONBhOgPr4sMhAVCoPx', 'N/A'),
          ('Turkce Rap', '37i9dQZF1DXdnOj1VEuhgb', 'Turkey'),
          ('Australia Top 50', '37i9dQZEVXbJPcfkRz0wJ0', 'Australia'),
          ('Latin Cardio', '37i9dQZF1DWXmQEAjlxGhi', 'N/A'),
          ('France Top 50', '37i9dQZEVXbIPWwFssbupI', 'France'),
          ('Shisha Club', '37i9dQZF1DX2lUf1uE6Mre', 'N/A'),
          ('Zona Trap', '37i9dQZF1DWXU2naFUn37x', 'N/A'),
          ('Trapeo', '37i9dQZF1DWXCGnD7W6WDX', 'Spain'),
          ('Marko musica', '629FVdSmGeEvClfrPPLXp3', 'N/A'),
          ('Turkey Top 50', '37i9dQZEVXbIVYVBNw9D5K', 'Turkey'),
          ('Hot Hits Turkey', '37i9dQZF1DX0FGW2dUyDef', 'Turkey'),
          ('Creamy', '37i9dQZF1DXdgz8ZB7c2CP', 'N/A'),
          ('Fresh Rap', '37i9dQZF1DWU4xkXueiKGW', 'France'),
          ('Latino Caliente', '1vIZxBcvgGHE9HXbQnzXYI', 'N/A'),
          ('VERANO 2020', '0Q5zVS7BXbPcFbCKMG74ik', 'N/A'),
          ('Tear Drop', '37i9dQZF1DX6xZZEgC9Ubl', 'N/A'),
          ('Colombia Top 50', '37i9dQZEVXbOa2lmxNORXQ', 'Colombia'),
          ('Sweden Top 50', '37i9dQZEVXbLoATJ81JYXz', 'Sweden'),
          ('Grand Hit', '37i9dQZF1DXcSPhLAnCjoM', 'N/A'),
          ('Rap Italia Battle', '37i9dQZF1DX14EWeH2Pwf3', 'Italy'),
          ('Exitos Colombia', '37i9dQZF1DXbvPjXfc8G9S', 'Colombia'),
          ('Hip Hop Club Bangers', '6fi0ExpvtWx0vQUelJkwmV', 'N/A'),
          ('Woordenschat', '37i9dQZF1DX19xRtMyA5LM', 'Netherlands'),
          ('Pop Urbaine', '37i9dQZF1DWYVURwQHUqnN', 'France'),
          ('REGUETON 2020 HITS ', '5tfMdUK5BYerybEtCL3Zxs', 'N/A'),
          ('Feelin Myself', '37i9dQZF1DX6GwdWRQMQpq', 'N/A'),
          ('Nuevo Flow', '37i9dQZF1DWZdsS73T1ogG', 'N/A'),
          ('Norway Top 50', '37i9dQZEVXbJvfa0Yxg7E7', 'Norway'),
          ('HipHop 2020‏‏​​‍', '5WNUX6jisX0NRlVDTm6RDd', 'N/A'),
          ('New Music Friday Latin', '37i9dQZF1DX1hVRardJ30X', 'Pinoy Rap', 'Philippines'),
          ('Deutschtrap', '37i9dQZF1DX2uJ1OVfn3CH', 'Germany'),
          ('Todo Reggaeton', '4csIMGPI3aGo3Xy7WG8jBi', 'Spain'),
          ('Rap in deep', '37i9dQZF1DX0Na9FTYame5', 'N/A'),
          ('Hip-Hop R&B Nation', '7kdOsNnHtzwncTBnI3J17w', 'N/A'),
          ('La Casa del Perreo', '37i9dQZF1DXb6wQUgoZzUc', 'N/A'),
          ('EXITOS del VERANO 2020', '5r6IfrLFMG4bmWpuuShEBq', 'N/A'),
          ('Exitos Peru', '37i9dQZF1DX9C8KzGEUKV4', 'Peru'),
          ('We Everywhere', '37i9dQZF1DWT6SJaitNDax', 'N/A'),
          ('Trapperz Argentina', '37i9dQZF1DWXrVH01e3PIE', 'Argentina'),
          ('Peru Top 50', '37i9dQZEVXbJfdy5b0KP7W', 'Peru'),
          ('Desi Hits', '37i9dQZF1DWTwzVdyRpXm1', 'N/A'),
          ('Chile Top 50', '37i9dQZEVXbL0GavIqMTeb', 'Chile'),
          ('Global X', '37i9dQZF1DWUxHPh2rEiHr', 'N/A'),
          ('Hiphop NL', '2PV3FWt2NEerKSgs3t2MpE', 'Netherlands'),
          ('Trapperz Brasil', '37i9dQZF1DWWr5uieiPUVM', 'Brazil'),
          ('Hit Italiane', '37i9dQZF1DXcuVttLeQxkh', 'Italy'),
          ('Italia in Alta', '37i9dQZF1DX01NP73ErE8b', 'Italy'),
          ('United States Viral 50', '37i9dQZEVXbKuaTI1Z1Afx', 'United States'),
          ('Trapperz', '37i9dQZF1DWUmxBdWX3Pp4', 'N/A'),
          ('Radar Brasil', '37i9dQZF1DWTVE8ZCcLQ5Q', 'Brazil'),
          ('New Music Friday AU NZ', '37i9dQZF1DWT2SPAYawYcO', 'Australia'),
          ('Canada Top 50', '37i9dQZEVXbKj23U1GF4IR', 'Canada'),
          ('Arena Hip-Hop', '37i9dQZF1DWVFZbCNivv6B', 'Mexico'),
          ('Cloud Rap', '37i9dQZF1DX5jNEiuvPyWr', 'France'),
          ('The Ultimate Trap', '2BXqqZ5kKMqfbwinU4AwIy', 'N/A'),
          ('Wilde Herzen', '37i9dQZF1DWSFDWzEZlALC', 'Germany'),
          ('K-Hip-Hop Beats', '37i9dQZF1DWW46Vfs1oltB', 'Korea'),
          ('Canta Sotto La Doccia', '37i9dQZF1DWVPKP49DU8tu', 'Italy'),
          ('Perreo City', '37i9dQZF1DWUlCmB8llCTB', 'N/A'),
          ('¡La Vida Loca!', '37i9dQZF1DWXHyhanaNMoy', 'Netherlands'),
          ('REGGETON 2020 HITS', '6ORz5P7KSzUdXw7Jq5AKty', 'N/A'),
          ('Pop Virale', '37i9dQZF1DWYCIYGXn56uz', 'Italy'),
          ('El Ritmo', '37i9dQZF1DWVOLXBOylBUZ', 'N/A'),
          ('Pool Party', '37i9dQZF1DX4gOolUyeDaQ', 'N/A'),
          ('Hip Hop Made Me', '3ZSq7rHkmA5m0suVh5z8lM', 'N/A'),
          ('Sanremo 2020', '37i9dQZF1DWVQfeA9N7Q0g', 'Italy'),
          ('Filtr Urban Hip Hop Party', '2PtnenL9aQ2oZlyJFEblq5', 'Germany'),
          ('Everyday Clout', '5lFi2bXdlrNo1rXlZHZa62', 'N/A'),
          ('Best TikTok Songs', '0kPkIECDhH4CMukogtp7Lc', 'N/A'),
          ('Urban Beats', '3gPKLkHC8eVJ0jlbxwABsP', 'N/A'),
          ('REGAETON 2020 HITS', '4B5rhAH80qM2Sj3wCyr0jC', 'N/A'),
          ('Workout Hip Hop Edition', '5TSQxc8pYO0pALA92qGXSh', 'N/A'),
          ('Harekete Gec', '37i9dQZF1DWZaiuILgorJB', 'Turkey'),
          ('Flow Selecto', '37i9dQZF1DX4OjfOteYnH8', 'N/A'),
          ('Worldstar Hip Hop Weekly', '58sBULwTsdblQI5EqOZ47C', 'N/A'),
          ('Road Trip To Tokyo', '37i9dQZF1DWV8IND7NkP2W', 'N/A'),
          ('Ireland Top 50', '37i9dQZEVXbKM896FDX8L1', 'Ireland'),
          ('Top Arabic Hits', '37i9dQZF1DX5cO1uP1XC1g', 'N/A'),
          ('REGGAETON NUEVO 2020', '27kNWmnl4NGluD6tlpBSb6', 'N/A'),
          ('Suave', '37i9dQZF1DWSjuSq42neMu', 'N/A'),
          ('Rap Essentials', '0zysvwomOYS5M1ceyE1rB7', 'N/A'),
          ('Daily Dope Music 2020', '6ATjjDPzGPWXTc5LxANZst', 'N/A'),
          ('Rap Acustico', '37i9dQZF1DWTf69iQOGkD2', 'Brazil'),
          ('Cumbia 2020', '3U1YBewRUskmLOGUINMvWG', 'Uruguay'),
          ('Mexico Viral 50', '37i9dQZEVXbLuUZrygauiA', 'Mexico'),
          ('BaitList', '5LwGTy1gOEG8SnvZb2s7pY', 'United Kingdom'),
          ('Poland Top 50', '37i9dQZEVXbN6itCcaL3Tt', 'Poland'),
          ('New Zealand Top 50', '37i9dQZEVXbM8SIrkERIYl', 'New Zealand'),
          ('Rap Fr', '0MF1XGKzqqeL0ZHeqMrq7R', 'France'),
          ('ISSA VIBE', '4JcbUMlNZBAgFpAFSAUeFE', 'N/A'),
          ('Novedades Viernes Espana', '37i9dQZF1DX6PYajiT4pAf', 'Spain'),
          ('Latin Urban Queens', '37i9dQZF1DX82VmYBD0zVC', 'N/A'),
          ('Pop Trap Hits', '4KqGF8hEgopXhDLnzqO0cM', 'N/A'),
          ('Trainingsboost mit Flying', '2rAakGLZTBYJ1Hjyadw0yK', 'Germany'),
          ('TOP 50 GLOBAL 2020', '2CJsD3fcYJWcliEKnwmovU', 'N/A'),
          ('¡Fiesta y Bailoteo!', '37i9dQZF1DX9H3lqBKp7yC', 'N/A'),
          ('Alles Gold Deutschrap', '3MpNPyX4mJ81tgNwL5XUcM', 'Germany'),
          ('Raptopia', '37i9dQZF1DWUQru3jd69v5', 'Italy'),
          ('Filtr Urban New Rap Hits', '3eSLbVDzysdwnbFjP52rA4', 'N/A'),
          ('Rap Worldwide', '3JC0qoGOcSzCN87wqJy3FB', 'N/A'),
          ('Rap 2020', '59rBMYukiDqbIOGsPgwagZ', 'N/A'),
          ('Dale Flow', '37i9dQZF1DX6sLKL3qdVO1', 'N/A'),
          ('Reggeton 2020 Para Bailar', '3PE8IzKiI37GBskprv69p1', 'N/A'),
          ('Portugal Top 50', '37i9dQZEVXbKyJS56d1pgi', 'Portugal'),
          ('Latin Hit Mix', '37i9dQZF1DXbLMw3ry7d7k', 'N/A'),
          ('Top Hits Hindi', '37i9dQZF1DX0XUfTFmNBRM', 'India'),
          ('TIK TOK SONGS YOU LOVE', '70zigMLHC6xxayqgePLGyA', 'N/A'),
          ('Spain Viral 50', '37i9dQZEVXbMfVLvbaC3bj', 'Spain'),
          ('HYPE MUSIC Best Hip Hop', '5zW7oFoZb0nZYJmQagegpQ', 'N/A'),
          ('Denmark Top 50', '37i9dQZEVXbL3J0k32lWnN', 'Denmark'),
          ('Generacja Hip Hop', '37i9dQZF1DWXJnyndhASBe', 'Poland'),
          ('Si Veo A Tu Mama', '0y2wNzIKsLYPEeATga4uwh', 'N/A'),
          ('Fissa', '5WZ951CGTTuOeay4c7jMsb', 'Netherlands'),
          ('Exitos 2020', '55lCjEKHyrO3wpLYD8Ktdo', 'Spain'),
          ('Hits MX', '5y7cKZqBaaAHYMR0fcsMyv', 'N/A'),
          ('Hip Hop Top Tracks', '4VgnM747kRrrIHnn3aNHBN', 'N/A'),
          ('Fiesta Hits', '7Mdq1Wpw4VWEeeLb7IYpEW', 'N/A'),
          ('Germany Viral 50', '37i9dQZEVXbNv6cjoMVCyg', 'Germany'),
          ('Trap Ouro', '37i9dQZF1DWYBXtbGSCurj', 'Brazil'),
          ('Reggaeton Mix 2020', '7eu1R4OMoFZ8xqgkHWpZHS', 'N/A'),
          ('Top Viral México', '37i9dQZF1DX4KeocBrdbJg', 'Mexico'),
          ('HIPHOP FIGURES', '6KYkiwUEsmEEkBShfe9VGB', 'N/A'),
          ('NEW RAP', '3dgqX01PXPxAoO93ZoJlJP', 'N/A'),
          ('Rap Nation', '6ZTpgxK6BT92mmsqwETj9l', 'N/A'),
          ('Presenca Hip Hop', '37i9dQZF1DX0jAiO33gxlI', 'Brazil'),
          ('Cachengue', '37i9dQZF1DWYNSDUeK85ev', 'N/A'),
          ('Urban Vibes', '0AjInv1X06Mx6HqLYWL4HT', 'Germany'),
          ('Fresh Variete', '37i9dQZF1DWSBZhfF4ZHr8', 'France'),
          ('Certi', '37i9dQZF1DX1eh709zIoRH', 'United Kingdom'),
          ('United Kingdom Viral 50', '37i9dQZEVXbL3DLHfQeDmV', 'United Kingdom'),
          ('RAP PROFILE', '19xQsxIqaiTaOR7zyG79Hs', 'N/A'),
          ('REGGEATON 2020', '4vZCzdgMj0tH8OA3bkGkVE', 'N/A'),
          ('DEUTSCHRAP BANGER by STOKED', '1G4xK6ksyXGLqkf4QSSQCL', 'N/A'),
          ('Hoy Se Sale', '2YEI1nY4VdJaFuFyOS0O13', 'Uruguay'),
          ('Its lit', '37i9dQZF1DWWmG4xgoLORa', 'Netherlands'),
          ('Ecuador Top 50', '37i9dQZEVXbJlM6nvL1nD1', 'Ecuador'),
          ('Hiphop NL', '4QZ4F2Yxc6RLx7ybP0Ozn4', 'Netherlands'),
          ('Worldstar Hip Hop Weekly', '18b9xG9IrqS8pIqWweSROb', 'United States'),
          ('Argentina Viral 50', '37i9dQZEVXbJajpaXyaKll', 'Argentina'),
          ('Filet Flows', '7n9VDHJMqpHhPHV07hWr0A', 'N/A'),
          ('Trapperz Mexa', '37i9dQZF1DXc5PHJQUwAnG', 'N/A'),
          ('TUNES HIGH LIFE', '3EyPEbfiDf2FZYnCZrFn3w', 'N/A'),
          ('Hip Hop 2020', '0OtdLZ5JVyqB4Zp8aylECe', 'N/A'),
          ('Regueton Nuevo 2020', '5ZDG0uIk7oGjdagnyBC4rM', 'N/A'),
          ('Hip Hop Hubspot', '6jRjnW7dD32u2wo8KUdTIK', 'N/A'),
          ('El Top 50 de Espana', '1JhllMCa5z4j6xEIpr7NfC', 'Spain'),
          ('Tik Tok Dance Songs', '3r4umM067bo3OvLWmzMZBQ', 'N/A'),
          ('Trap strefa', '37i9dQZF1DWY3UKS6jvnxr', 'N/A'),
          ('REGUETON 2020', '66WFalGuFXfed3D87cFGzA', 'N/A'),
          ('Workout Hits', '793uPevBrp5ELc7K5qCRCR', 'N/A'),
          ('Perreo intenso', '0CyJwbNloGreP5itrOhugV', 'N/A'),
          ('RnB Hits 2020', '6y37llELgriD8YWdBlqA0m', 'N/A'),
          ('Rap Francais 2020', '4l1CEhc7ZPbaEtiPdCSGbl', 'France'),
          ('KMN ist die Gang', '6Lg0ysd5jDcp7xcFGRbcy9', 'Germany'),
          ('Latin Vibes', '5VusvMk3aK3O13G6K8JB7B', 'N/A'),
          ('Rap Tuga', '37i9dQZF1DXdpF2suW27SP', 'Portugal'),
          ('Argentina Top 50', '1Yv91P93nQt48TYWDwzhbH', 'Argentina'),
          ('2020 Hip Hop Rap', '2NuAWjvV3f49BIsyZs8YW2', 'N/A'),
          ('Dominican Republic Top 50', '37i9dQZEVXbKAbrMR8uuf7', 'Dominican Republic'),
          ('Je Moerstaal', '37i9dQZF1DWUX3x84bv557', 'Netherlands'),
          ('Prende La Fiesta!', '7w2lCOvxZwvJCkwuDin8N2', 'N/A'),
          ('BooskaBangers', '3IZplelTo9IHzZOd1bCEbU', 'France'),
          ('Northern Bars', '37i9dQZF1DX59ogDi1Z2XL', 'Canada'),
          ('Germany Top 50', '6wLRbQ8ujPUjIoX86uDVxJ', 'Germany'),
          ('Colombia Top 50', '4n73IOcoFlkg1vVcXTLpTC', 'Colombia'),
          ('Finland Top 50', '37i9dQZEVXbMxcczTSoGwZ', 'Finland'),
          ('Brisa Pop', '37i9dQZF1DX2vsux22VuNL', 'Brazil'),
          ('Austria Top 50', '37i9dQZEVXbKNHh6NIXu36', 'Austria'),
          ('Switzerland Top 50', '37i9dQZEVXbJiyhoAPEfMK', 'Switzerland'),
          ('POP Hits 2020', '2XoI3YdTdg3qK1aWX2lxt4', 'N/A'),
          ('Lo Que Suena', '37i9dQZF1DXctZGldNPWLR', 'N/A'),
          ('Rep The Set', '5HYnMEFnXw6j9Xj8DIth0f', 'N/A'),
          ('RnB Brasil', '37i9dQZF1DX6EQe4DjJNfI', 'Brazil'),
          ('Sunset Volume', '7Ml17ir7ugzs9mCB5rFjn6', 'N/A'),
          ('Lo Mejor del 2020', '3mn4kXt07PEGZFR46h3HhN', 'Spain'),
          ('Italy Top 50', '78IK6mkyLgvQYwtAkmggYT', 'Italy'),
          ('Lyricistes', '37i9dQZF1DX0AgrgHFR9aa', 'France'),
          ('vainsuomihitit', '37i9dQZF1DWUvzPS8uIABd', 'Finland'),
          ('Costa Rica Top 50', '37i9dQZEVXbMZAjGMynsQX', 'Costa Rica'),
          ('Buen Vibe', '37i9dQZF1DXbT1642xPu6H', 'N/A'),
          ('Rap Italiano Game Over', '7Ceoy51Sq3rYXlr8KFSJkj', 'Italy'),
          ('The State of TrapRap', '2kAETxkq1AUopKWOOU5sx8', 'N/A'),
          ('UK FLEX', '5njm69gKd9t3RzpBFafjOL', 'United Kingdom'),
          ('Motive', '37i9dQZF1DWVt4VCv1XXbY', 'N/A'),
          ('RAP LAND', '2MePNY9Eq3pqejbIA3SP9u', 'N/A'),
          ('Hits Latinos 2020', '3oBf7jbb5tokVOYQVGIUAg', 'N/A'),
          ('Local Hype', '37i9dQZF1DWUjxn1SsdJYZ', 'Australia'),
          ('Flow al Sur', '37i9dQZF1DX6JcLkkShqRw', 'N/A'),
          ('UK Drill', '2HTUlfY8F4BhDwd8ad38ki', 'United Kingdom'),
          ('Vibes', '37i9dQZF1DX2BCjruDQhfl', 'Netherlands'),
          ('Vip', '37i9dQZF1DWZLK2btdLMWz', 'N/A'),
          ('TIKTOK and TRILLER', '4HMzTh4diXJPRQDWQ7qo09', 'N/A'),
          ('Plvylists Aux', '3YmrYSqTD5udiEDduALNFK', 'N/A'),
          ('2020 Rap and Hip Hop', '3MhSDPy3PXAQMORRE4EeXL', 'N/A'),
          ('tiktok songs that you will love', '1y033SLUSiJ0H2uwb3xAo0', 'N/A'),
          ('Rap E Compromisso', '4eoAeASXEEa3s8CC5SVsCH', 'N/A'),
          ('Rap Reflection', '0umAjCrPnONPCcLcZq0epU', 'N/A'),
          ('Trap Funk', '37i9dQZF1DWTGaQ84g8alz', 'Brazil'),
          ('Flow Latino', '4hAmaWPsntG17RJPZbAENM', 'Colombia'),
          ('ESPANA TOP 50', '7ki8VipxMygh7Y8ZdPRvmX', 'Spain'),
          ('Latinos De Fiesta', '6iP66p2aJ7DmWcma2OnRCT', 'Argentina'),
          ('DripDrop', '4MuEd7ylRz8O6u67ayDCzw', 'N/A'),
          ('Madrugada SadSongs', '37i9dQZF1DX0H97kz3DdJ6', 'Brazil'),
          ('No Role', '0jwrUmA1q2XedkzDBvoHC4', 'N/A'),
          ('African Heat', '37i9dQZF1DWYkaDif7Ztbp', 'South Africa'),
          ('Next Wave Neo-Soul', '37i9dQZF1DX44dZ4p5QLf4', 'South Africa'),
          ('Weekly Afrobeats Top 100', '6Dh0MkO3XzQr0txvSS7OmJ', 'South Africa'),
          ('Afro Hits', '37i9dQZF1DWX0o6sD1a6P5', 'France'),
          ('AFROBEATS 2020', '6bnfXsKx2VA8Mx8kheMuhj', 'N/A'),
          ('Future Hits', '6Ek1eTWRVXuSFM9lSc7LlA', 'N/A'),
          ('Chop Daily', '7o9c6BlZsFhADJArho1Phf', 'N/A'),
          ('Afrobeats Summer 2020', '72D7RInsvGTAk1QfCAaBjF', 'N/A'),
          ('FIRE EMOJI', '07NwKRH1pMbdHtxbI4OuVh', 'N/A'),
          ('Naija', '2n8POxkiNjLibFSTwe4u7p', 'N/A'),
          ('Basshall Movement', '5QEyEN3hfsgdZdEiCajdKl', 'N/A'),
          ('Todo Urban', '6Sv099SIT6fSp6y0GOx4Ud', 'N/A'),
          ('On Our Radar', '37i9dQZF1DWY0DyDKedRYY', 'N/A'),
          ('Dancehall Mix', '1Pc5ExsgvUdkne29mAVvNJ', 'N/A'),
          ('HYPEBEAST', '2uCwoflOUSLK0cbr6sC8qS', 'N/A'),
          ('African VibeS', '74CNNE0aWi32veKswDBdNa', 'N/A'),
          ('Best of AFROBEATS', '2Wiuv2NCeRYbP5fJYr5eVs', 'N/A'),
          ('NEW AFROBEATS', '2DfNaw9Z1nuddjI6NczTXS', 'N/A'),
          ('Afrobeats 100', '39BnLVziHWxVP7y7fafSvV', 'N/A'),
          ('Afropop', '37i9dQZF1DWYs2pvwxWA7l', 'N/A'),
          ('Afro Party Anthems', '37i9dQZF1DWSjibQnF0bUk', 'N/A'),
          ('Tantalizers', '37i9dQZF1DWU4DdJqbjPl5', 'N/A'),
          ('NIGERIAN MUSIC 2020', '5oLoDUUcDfJPfMXuwXMiXb', 'Nigeria'),
          ('Afro Heat Naija', '71SBzf9OAv1sgupI1oyhur', 'N/A'),
          ('So as Minas', '37i9dQZF1DXe4mpNXfrVqx', 'Brazil'),
          ('Perreo 2019', '61abC9buqDi0uE5WOX3eed', 'N/A'),
          ('Tik Tok Songs Memes', '2FttbYCKDE5LWKgenB6BLb', 'N/A'),
          ('FRONTLINE HIP HOP', '21rJsjyo2aqptZOwrvf10N', 'N/A'),
          ('BASS BOOSTED', '1GwvW3po7ygdbqqR045Jty', 'N/A'),
          ('REGAETON 2020 HITS', '67PukwGmbdPiY1efXc92Nx', 'N/A'),
          ('Car Rap Trap and Bass', '19lzYOlmQsXo5d1A2ykI1g', 'N/A'),
          ('Reggaeton Para La Fiesta', '2jZiuUentfDZFFGEWlXWta', 'N/A'),
          ('Hip Hop Argento', '37i9dQZF1DX2v4h8QERQPb', 'Argentina'),
          ('Monday to Monday', '052XtM0s4GQ8n8xXp60ryw', 'United States'),
          ('DK rap', '37i9dQZF1DXdhDukKQ88Cc', 'Denmark'),
          ('Rap Internacional 2020', '1Pcsy7nOw1nbEvWm1w3ZJ9', 'N/A'),
          ('Chill vibes', '3XtUu7oYDMg0Lyr52rBtvs', 'N/A'),
          ('Graffiti Pop', '37i9dQZF1DX0tIXxCeVLSQ', 'N/A'),
          ('Dar el Rol', '37i9dQZF1DXbONvB5b3uef', 'N/A')
          ]

latinIds = [('MIRREY', '37i9dQZF1DWXYhWcTBGc47'),
('Fiesta', '37i9dQZF1DX9vJ2U3sN7xj'), ('Mas Que Amigos', '37i9dQZF1DX3llIQ4rouPW'), ('Viral Latino', '37i9dQZF1DX5y71ufjoyXC'),
('Fiesta Fiesta', '37i9dQZF1DX9KJJbsGEwfj'), ('Argentina Top 50', '37i9dQZEVXbMMy2roB9myp'), ('Pop con N', '37i9dQZF1DX3sCT1ItXgNd'),
('Vibras', '37i9dQZF1DWT34oeYRnJ0R'), ('Latin Cardio', '37i9dQZF1DWXmQEAjlxGhi'), ('Trapeo', '37i9dQZF1DWXYhWcTBGc47'),
('Marko musica', '629FVdSmGeEvClfrPPLXp3'), ('Mueve Tu Cuerpo', '37i9dQZF1DWT2VB7HB29Jj'), ('Perrear y Llorar', '37i9dQZF1DWXYWuNDAdJsw'),
('Latino Caliente', '1vIZxBcvgGHE9HXbQnzXYI'), ('VERANO', '0Q5zVS7BXbPcFbCKMG74ik'), ('Colombia Top 50', '37i9dQZEVXbOa2lmxNORXQ'),
('Éxitos Colombia', '37i9dQZF1DXbvPjXfc8G9S'), ('En el Trabajo', '37i9dQZF1DX62RIcEOaBWi'), ('Reggaeton2', '5tfMdUK5BYerybEtCL3Zxs'),
('Cafe con Leche', '37i9dQZF1DXa3NnZWk6Z3T'), ('Nuevo Flow', '37i9dQZF1DWZdsS73T1ogG'), ('New Music Friday Latin', '37i9dQZF1DX1hVRardJ30X'),
('Paraiso Tropical', '37i9dQZF1DWYey22ryYM8U'), ('Enamorandose', '37i9dQZF1DX14fkzxPABaL'), ('Mas Motivacion', '37i9dQZF1DX3NRlBOcUOcY'),
('Todo Reggaeton', '4csIMGPI3aGo3Xy7WG8jBi'), ('La Casa del Perreo', '37i9dQZF1DXb6wQUgoZzUc'), ('Latin Divas', '37i9dQZF1DX5AVYhCeISA6'),
('Premios Juventud 2019', '37i9dQZF1DWWdqmyKhfIrN'), ('Reggaeton3', '5r6IfrLFMG4bmWpuuShEBq'), ('Exitos Peru', '37i9dQZF1DX9C8KzGEUKV4'),
('Popeton', '37i9dQZF1DWTPDzakLfYZr'), ('Trapperz Argentina', '37i9dQZF1DWXrVH01e3PIE'), ('Peru Top 50', '37i9dQZEVXbJfdy5b0KP7W'),
('Made in Colombia', '37i9dQZF1DX5UTavgI6ivn'), ('Chile Top 50', '37i9dQZEVXbL0GavIqMTeb'), ('Trappperz', '37i9dQZF1DWUmxBdWX3Pp4'),
('Mucho Rap', '37i9dQZF1DWTgSTuHRv7LV'), ('Reggaeton4', '3H1yE5z56AjkLfVtm8qsWW'), ('Rap Espanol', '37i9dQZF1DXcd2Vmhfon1w'),
('Arena Hip-Hop', '37i9dQZF1DWVFZbCNivv6B'), ('Bachata', '5SqR3iQ1rvzjjB8vEPlF8d'), ('Pop Spain', '0Ch8LdZiJuSqUvRsASqrjS'),
('lo del vallenato', '37i9dQZF1DXdzp8aTdsnVq'), ('baila y perrea', '0Bwc1QkTF2EddMIhwRIiae'), ('MIRREY', '37i9dQZF1DWXYhWcTBGc47'),
('rap chileno', '37i9dQZF1DXdxFkXW4j8RX'), ('Perreo City', '37i9dQZF1DWUlCmB8llCTB'), ('El Bloque', '37i9dQZF1DWW3mVKqVYIFi'),
('reggaeton5', '6ORz5P7KSzUdXw7Jq5AKty'), ('Pool Party', '37i9dQZF1DX4gOolUyeDaQ'), ('El Ritmo', '37i9dQZF1DWVOLXBOylBUZ'),
('Te Quiero', '37i9dQZF1DX6rXTaz81RRT'), ('a bailar', '3JwPVKISB9IBlE2RST1MVn'), ('zumba', '2SfLSuD1i4z67jGqVTtIcE'),
('reggaeton6', '0WN0RmIro8C69bFPbIxAY2'), ('Tropical Rising', '37i9dQZF1DX07X8UDWKEwP'), ('reggaeton7', '4B5rhAH80qM2Sj3wCyr0jC'),
('flamenco pop', '37i9dQZF1DWV7FWPDK0Dg1'), ('latin pop rising', '37i9dQZF1DX8womvTyUjrN'), ('reggaeton8', '27kNWmnl4NGluD6tlpBSb6'),
('suave', '37i9dQZF1DWSjuSq42neMu'), ('cumbia 2020', '3U1YBewRUskmLOGUINMvWG'), ('mexico viral 50', '37i9dQZEVXbLuUZrygauiA'),
('novedades viernes espana', '37i9dQZF1DX6PYajiT4pAf'), ('latin urban queens', '37i9dQZF1DX82VmYBD0zVC'), ('radio corazon', '37i9dQZF1DWSF59R74xaFB'),
('fiesta y bailoteoo', '37i9dQZF1DX9H3lqBKp7yC'), ('romanticas en espanol', '4RZHGMiPzjc0tjTaKhHuiv'), ('canciones que lo petan', '5jtCTvfTMl87Dwfm9rpX6d'),
('dale flow', '37i9dQZF1DX6sLKL3qdVO1'), ('reggaeton9', '3PE8IzKiI37GBskprv69p1'), ('latin hit mix', '37i9dQZF1DXbLMw3ry7d7k'),
('hora de la comida', '37i9dQZF1DXa0xldXwsLda'), ('la tribu', '03NhLmKCCedKbwRCCtM73H'), ('spain viral 50', '37i9dQZEVXbMfVLvbaC3bj'),
('reggaeton10', '0si5tw70PIgPkY1Eva6V8f'), ('si veo a tu mama', '0y2wNzIKsLYPEeATga4uwh'), ('coloresjbalvin', '5bXfhlaTomVGJNQwnxthDh'),
('exitos2020', '55lCjEKHyrO3wpLYD8Ktdo'), ('hits mex', '5y7cKZqBaaAHYMR0fcsMyv'), ('fiesta hits', '7Mdq1Wpw4VWEeeLb7IYpEW'),
('latin grammy awards', '37i9dQZF1DX5qGup0t1SY0'), ('spanish hits 2020', '5khoF3ksobwfVwOazDqpqI'), ('reggaeton11', '7eu1R4OMoFZ8xqgkHWpZHS'),
('top viral mexico', '37i9dQZF1DX4KeocBrdbJg'), ('canciones para abrrer', '6doxLXobVwUTcTHMZykFRu'), ('40 hitts', '2w90Jrb5nmYNzUYqv7DdBy'),
('exitos del verano 2020 dama', '1kWCcnLakmQ4jAbh0rpAh5'), ('cachengue', '37i9dQZF1DWYNSDUeK85ev'), ('reggaeton12', '5X1gvBHkeLZznkQta5NNTv'),
('vivalatino', '37i9dQZF1DX10zKzsJ2jva'), ('baila reggaeton', '37i9dQZF1DWY7IeIP1cdjF'), ('veranoforever', '37i9dQZF1DXdnGF35OawbN'),
('baladas romanticas', '37i9dQZF1DX09mi3a4Zmox'), ('exitos mexico', '37i9dQZF1DX5BAPG29mHS8'), ('los que mandan40', '37i9dQZF1DXb0COFso7q0D'),
('canciones del recuerdo', '37i9dQZF1DX20VDU4OIBfS'), ('exitos espnana', '37i9dQZF1DXaxEKcoCdWHD'), ('exitos argentina', '37i9dQZF1DXbbu94YBG7Ye'),
('esenciales', '37i9dQZF1DX3omIq8ziEt6'), ('latin party anthems', '37i9dQZF1DWVcbzTgVpNRm'), ('mint latin', '37i9dQZF1DX07RJCJCOYpi'),
('latin pop vip', '37i9dQZF1DX1QnNyJOBQBv'), ('amor amor camilo', '37i9dQZF1DWUoGbRYcteyC'), ('exitos usa', '37i9dQZF1DX4oUPBOaEkL6'),
('sin ti', '37i9dQZF1DX4yeSNLFx6qI'), ('mansion reggaeton', '37i9dQZF1DWZjqjZMudx9T'), ('trap land', '37i9dQZF1DXde9tuMHuIsj'),
('zumbazumba', '37i9dQZF1DX7cmFV9rWM0u'), ('canta en la ducha', '37i9dQZF1DX8CTD7HWYPDn'), ('exitos chile', '37i9dQZF1DXclgCwbk0uat'),
('canta en la ducha', '37i9dQZF1DX8CTD7HWYPDn'), ('radar latino', '37i9dQZF1DWZoF06RIo9el'), ('mediodia acustico', '37i9dQZF1DWWoDbniQLBJY'),
('reggaeton14', '7xWuNevFBmwnFEg6wzdCc7'), ('hits alegres', '37i9dQZF1DX9Dh2wgiAwVX'), ('solo pop', '37i9dQZF1DX4YhSbTs17ha'),
('fuego', '37i9dQZF1DX8sljIJzI0oo'), ('spain top 50', '37i9dQZEVXbNFJfN1Vw8d9'), ('puro perreo', '37i9dQZF1DWX5ZOsG2Ogi1'),
('mexicotop50', '37i9dQZEVXbO3qyFxbkOE1'), ('duetos', '37i9dQZF1DX4nV8QNjO7nb'), ('hits urbanos', '37i9dQZF1DWVskFRGurTfg'),
('despierta y sonrie', '37i9dQZF1DWVhcOv4ieuap')]


portIds = [('so as minas', '37i9dQZF1DXe4mpNXfrVqx'),
('madrugada sadsongs', '37i9dQZF1DX0H97kz3DdJ6'), ('alma pagoderia', '37i9dQZF1DXaxIuRWwYocy'), ('trapando', '37i9dQZF1DX6PsvyweoPP8'),
('hits verao2020', '5HmZtuuIDMtIy21kylqhx6'), ('sertanejouniverse', '4EsLmFhEomsL1fCqwFZQhP'), ('flow brasiliero', '37i9dQZF1DX7f8PyAQL3rz'),
('dose trap', '37i9dQZF1DWWlW7KLhEhCZ'), ('rap tuga', '37i9dQZF1DXdpF2suW27SP'), ('tophitsport', '0YK2R0IF7WrSbo8uB4a5Eb'),
('portugaltophits', '6sSDwZCMnILlhfHnK0pxaW'), ('radar brasil', '37i9dQZF1DWTVE8ZCcLQ5Q'), ('brazil viral 50', '37i9dQZEVXbMOkSwG072hV'),
('brega funk', '37i9dQZF1DWZgZxLup5qYy'), ('festa na piscina', '37i9dQZF1DXdWpx7KRCSbJ'), ('baile funk2020', '4ut6RdaC7vEH5SpI5MXnnT'),
('forronejo', '37i9dQZF1DXbkU0pC52xDz'), ('sol e churrasco', '37i9dQZF1DXb1oSegSL8id'), ('pagode2020melhores', '44rrWDJeyqOx4SVvUI3kZU'),
('sertanejoraiz', '37i9dQZF1DWXeSNtpjKSsO'), ('maistocadas2020', '2UgUYCjD5nuBGyWRaWBoUf'), ('alvxaro', '1qNvW0x1LvDI6GmNYPXM8u'),
('top100 brasil', '6TJtYZm7f40ed3xLBHN0p2'), ('showdas poderosas', '37i9dQZF1DWTSW6EnevZMi'), ('as melhores 2020', '27KCnBs5sZTXgaF4WIy5XQ'),
('rap acustico', '37i9dQZF1DWTf69iQOGkD2'), ('funk2o20', '1rjCkO3uhxg6DvuKGQ5Uou'), ('chiclete', '0xqkC5H1oerl14tBctvN3z'),
('festa na praia', '37i9dQZF1DX41UmHm2vtav'), ('lacradorxs', '37i9dQZF1DWZylNQMXNhNe'), ('trap ouro', '37i9dQZF1DWYBXtbGSCurj'),
('vibracoes positivas', '5rf6EYSgoY0285PL9wcHxT'), ('presenca hip hop', '37i9dQZF1DX0jAiO33gxlI'), ('top mais tocadas', '3FEfhg5eUYoNIMAvErsNn6'),
('funk hits', '37i9dQZF1DWTkIwO2HDifB'), ('pop up', '37i9dQZF1DX6aTaZa0K6VA'), ('braziltop50', '37i9dQZEVXbMXbN3EUUhlg'),
('pop brasil', '37i9dQZF1DWVLcZxJO5zyf'), ('bonde do funk', '37i9dQZF1DWYYeOy9vs7I5'), ('Pagodeira', '37i9dQZF1DWVjNkaVEkL3X'),
('hip hop crew', '37i9dQZF1DXb8e91bM8R51'), ('nacao reggae', '37i9dQZF1DWTMlvEhEJDRB'), ('Indie Brasil', '37i9dQZF1DWZi7MSnECo7D'),
('treino hip hop', '37i9dQZF1DX9wPYtCQ8Q0s'), ('brisa pop', '37i9dQZF1DX2vsux22VuNL'), ('rnbbrazil', '37i9dQZF1DX6EQe4DjJNfI'),
('farra sertaneja', '37i9dQZF1DX5GJ0BQvLMjM'), ('sertanejo2020marco', '68kJ4ASW7AWdDKMiC3C7mC'), ('funk pop', '37i9dQZF1DWW6EwN6CPxGO'),
('bom dia sertanejo', '37i9dQZF1DX1fiLEx7ZFmY'), ('trapperz brasil', '37i9dQZF1DWWr5uieiPUVM'), ('sertanejo2020mais', '4ApmKHtHuz8ToUrz6OOPf3'),
('cantando no chuviero', '37i9dQZF1DWWrDntpgyzu9'), ('Funknejo', '37i9dQZF1DWZLiXDryu4Fe'), ('topbrasil', '37i9dQZF1DX0FOF1IUWK1W'),
('braziltop50', '37i9dQZEVXbMXbN3EUUhlg'), ('rapublica', '37i9dQZF1DWSIvbYYt1Dvi')]


frenchIds = [('LE CONCENTRE', '0lLJYcd09ALDXsd66bd6Mt'),
('French Music 2020', '0gV0dmlVlo0cShIA5Qw9YR'), ('RAPUNCHLINE', '44S09uTRLrW1xph1JD5lKJ'), ('Planete Rap 2020', '1BztaAUFxghyOdmwPlJwwk'),
('A LA FRANcAISE', '11ZL0eDMbPxMfLd4mNnUFj'), ('France Top 50', '6xnfRIFfuYOfWqJivjUPNz'), ('Rap FR sorties du', '7rn2o6gP7zXaRR9lq93Klk'),
('AloneList', '167iCb4j4Yc35hM21RB495'), ('Pop Urbaine1', '1iY9dbMVfyjMxAo7ubJgEa'), ('Vice Versa', '37i9dQZF1DX9h4FeDa1xsw'),
('ESSE MAGAZINE', '2OYC0si1BOH6YOVgFTJOJl'), ('Pop Urbaine2', '3aj8I39Ok1hAmzRDJ0KYPH'), ('Valise', '6rA9RBfWprvjwx7fzZN6pK'),
('Masilia2007', '0jwhhs6I328aa23hMaXVp7'), ('rnbae', '37i9dQZF1DX2LoIIQLAhdb'), ('Top 50 France2', '23psvx6vUY6pmJHxE5yagM'),
('En Mode Rap', '0qylIR3cDeMuvyltTYMZmH'), ('French Rap2', '0gjOliftUAwV48X6KK9EeP'), ('NUITVIE', '0YZKARsIjxhByr84Jre1le'),
('BooskaHits', '7AlnYDOvpzRnfC3DeSj6Vz'), ('Declasse', '37i9dQZF1DX4WpYT2fah9c'), ('Habibi Gang Gang', '37i9dQZF1DX3MGdnF1V53j'),
('franceviral50', '37i9dQZEVXbJmRv5TqJW16'), ('Rap Corner', '4qKKSgcuPJ9D1DGwAAqquG'), ('Urbain France3', '11c9NkgEextzc7hrqO08ld'),
('Rap Diggers', '37i9dQZF1DX9PXZbuB8BjJ'), ('Grand Hit', '37i9dQZF1DXcSPhLAnCjoM'), ('New Music Friday France', '37i9dQZF1DX742okrrpwah'),
('Rap Fr2', '0MF1XGKzqqeL0ZHeqMrq7R'), ('Culture Tubes', '37i9dQZF1DWVAWlq3l00p0'), ('Chicha Royale', '37i9dQZF1DX32nf7PAbnUl'),
('Fresh Variete', '37i9dQZF1DWSBZhfF4ZHr8'), ('Rap Francais 2020', '4l1CEhc7ZPbaEtiPdCSGbl'), ('Lyricistes', '37i9dQZF1DX0AgrgHFR9aa'),
('Rap France 2k20', '1cSWAkW9XyjiG67wLtb2bU'), ('Rap Bangies', '4J75l0Bc0dXoqSeSa29zKJ'), ('EuroLatino', '37i9dQZF1DXaR954ExpGKR'),
('Valid3e', '37i9dQZF1DX4sJFeoGlF41'), ('Arab X', '37i9dQZF1DWWkrGNlIHxPl'), ('PVNCHLNRS', '37i9dQZF1DX1X23oiQRTB5'),
('Fresh Rap', '37i9dQZF1DWU4xkXueiKGW'), ('Afro Hits', '37i9dQZF1DWX0o6sD1a6P5'), ('Cloud Rap', '37i9dQZF1DX5jNEiuvPyWr'),
('lafaceb', '37i9dQZF1DWWGfAvkwMeip'), ('Moha La Squale', '7LbvtJx0KK19pBqOdvvwP8')]